# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['AccountArgs', 'Account']

@pulumi.input_type
class AccountArgs:
    def __init__(__self__, *,
                 handle: pulumi.Input[_builtins.str],
                 domain_names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 link: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 settings: Optional[pulumi.Input['AccountSettingsArgs']] = None):
        """
        The set of arguments for constructing a Account resource.

        :param pulumi.Input[_builtins.str] handle: Unique handle of the account
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domain_names: The list of domain names for enabling SSO in Prefect Cloud.
        :param pulumi.Input[_builtins.str] link: An optional for an external url associated with the account, e.g. https://prefect.io/
        :param pulumi.Input[_builtins.str] location: An optional physical location for the account, e.g. Washington, D.C.
        :param pulumi.Input[_builtins.str] name: Name of the account
        :param pulumi.Input['AccountSettingsArgs'] settings: Group of settings related to accounts
        """
        pulumi.set(__self__, "handle", handle)
        if domain_names is not None:
            pulumi.set(__self__, "domain_names", domain_names)
        if link is not None:
            pulumi.set(__self__, "link", link)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if settings is not None:
            pulumi.set(__self__, "settings", settings)

    @_builtins.property
    @pulumi.getter
    def handle(self) -> pulumi.Input[_builtins.str]:
        """
        Unique handle of the account
        """
        return pulumi.get(self, "handle")

    @handle.setter
    def handle(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "handle", value)

    @_builtins.property
    @pulumi.getter(name="domainNames")
    def domain_names(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The list of domain names for enabling SSO in Prefect Cloud.
        """
        return pulumi.get(self, "domain_names")

    @domain_names.setter
    def domain_names(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "domain_names", value)

    @_builtins.property
    @pulumi.getter
    def link(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        An optional for an external url associated with the account, e.g. https://prefect.io/
        """
        return pulumi.get(self, "link")

    @link.setter
    def link(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "link", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        An optional physical location for the account, e.g. Washington, D.C.
        """
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the account
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def settings(self) -> Optional[pulumi.Input['AccountSettingsArgs']]:
        """
        Group of settings related to accounts
        """
        return pulumi.get(self, "settings")

    @settings.setter
    def settings(self, value: Optional[pulumi.Input['AccountSettingsArgs']]):
        pulumi.set(self, "settings", value)


@pulumi.input_type
class _AccountState:
    def __init__(__self__, *,
                 created: Optional[pulumi.Input[_builtins.str]] = None,
                 domain_names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 handle: Optional[pulumi.Input[_builtins.str]] = None,
                 link: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 settings: Optional[pulumi.Input['AccountSettingsArgs']] = None,
                 updated: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Account resources.

        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domain_names: The list of domain names for enabling SSO in Prefect Cloud.
        :param pulumi.Input[_builtins.str] handle: Unique handle of the account
        :param pulumi.Input[_builtins.str] link: An optional for an external url associated with the account, e.g. https://prefect.io/
        :param pulumi.Input[_builtins.str] location: An optional physical location for the account, e.g. Washington, D.C.
        :param pulumi.Input[_builtins.str] name: Name of the account
        :param pulumi.Input['AccountSettingsArgs'] settings: Group of settings related to accounts
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        """
        if created is not None:
            pulumi.set(__self__, "created", created)
        if domain_names is not None:
            pulumi.set(__self__, "domain_names", domain_names)
        if handle is not None:
            pulumi.set(__self__, "handle", handle)
        if link is not None:
            pulumi.set(__self__, "link", link)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if settings is not None:
            pulumi.set(__self__, "settings", settings)
        if updated is not None:
            pulumi.set(__self__, "updated", updated)

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter(name="domainNames")
    def domain_names(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The list of domain names for enabling SSO in Prefect Cloud.
        """
        return pulumi.get(self, "domain_names")

    @domain_names.setter
    def domain_names(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "domain_names", value)

    @_builtins.property
    @pulumi.getter
    def handle(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unique handle of the account
        """
        return pulumi.get(self, "handle")

    @handle.setter
    def handle(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "handle", value)

    @_builtins.property
    @pulumi.getter
    def link(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        An optional for an external url associated with the account, e.g. https://prefect.io/
        """
        return pulumi.get(self, "link")

    @link.setter
    def link(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "link", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        An optional physical location for the account, e.g. Washington, D.C.
        """
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the account
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def settings(self) -> Optional[pulumi.Input['AccountSettingsArgs']]:
        """
        Group of settings related to accounts
        """
        return pulumi.get(self, "settings")

    @settings.setter
    def settings(self, value: Optional[pulumi.Input['AccountSettingsArgs']]):
        pulumi.set(self, "settings", value)

    @_builtins.property
    @pulumi.getter
    def updated(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @updated.setter
    def updated(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated", value)


@pulumi.type_token("prefect:index/account:Account")
class Account(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain_names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 handle: Optional[pulumi.Input[_builtins.str]] = None,
                 link: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 settings: Optional[pulumi.Input[Union['AccountSettingsArgs', 'AccountSettingsArgsDict']]] = None,
                 __props__=None):
        """
        Create a Account resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domain_names: The list of domain names for enabling SSO in Prefect Cloud.
        :param pulumi.Input[_builtins.str] handle: Unique handle of the account
        :param pulumi.Input[_builtins.str] link: An optional for an external url associated with the account, e.g. https://prefect.io/
        :param pulumi.Input[_builtins.str] location: An optional physical location for the account, e.g. Washington, D.C.
        :param pulumi.Input[_builtins.str] name: Name of the account
        :param pulumi.Input[Union['AccountSettingsArgs', 'AccountSettingsArgsDict']] settings: Group of settings related to accounts
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AccountArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Account resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AccountArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AccountArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain_names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 handle: Optional[pulumi.Input[_builtins.str]] = None,
                 link: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 settings: Optional[pulumi.Input[Union['AccountSettingsArgs', 'AccountSettingsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AccountArgs.__new__(AccountArgs)

            __props__.__dict__["domain_names"] = domain_names
            if handle is None and not opts.urn:
                raise TypeError("Missing required property 'handle'")
            __props__.__dict__["handle"] = handle
            __props__.__dict__["link"] = link
            __props__.__dict__["location"] = location
            __props__.__dict__["name"] = name
            __props__.__dict__["settings"] = settings
            __props__.__dict__["created"] = None
            __props__.__dict__["updated"] = None
        super(Account, __self__).__init__(
            'prefect:index/account:Account',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            created: Optional[pulumi.Input[_builtins.str]] = None,
            domain_names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            handle: Optional[pulumi.Input[_builtins.str]] = None,
            link: Optional[pulumi.Input[_builtins.str]] = None,
            location: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            settings: Optional[pulumi.Input[Union['AccountSettingsArgs', 'AccountSettingsArgsDict']]] = None,
            updated: Optional[pulumi.Input[_builtins.str]] = None) -> 'Account':
        """
        Get an existing Account resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domain_names: The list of domain names for enabling SSO in Prefect Cloud.
        :param pulumi.Input[_builtins.str] handle: Unique handle of the account
        :param pulumi.Input[_builtins.str] link: An optional for an external url associated with the account, e.g. https://prefect.io/
        :param pulumi.Input[_builtins.str] location: An optional physical location for the account, e.g. Washington, D.C.
        :param pulumi.Input[_builtins.str] name: Name of the account
        :param pulumi.Input[Union['AccountSettingsArgs', 'AccountSettingsArgsDict']] settings: Group of settings related to accounts
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AccountState.__new__(_AccountState)

        __props__.__dict__["created"] = created
        __props__.__dict__["domain_names"] = domain_names
        __props__.__dict__["handle"] = handle
        __props__.__dict__["link"] = link
        __props__.__dict__["location"] = location
        __props__.__dict__["name"] = name
        __props__.__dict__["settings"] = settings
        __props__.__dict__["updated"] = updated
        return Account(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter(name="domainNames")
    def domain_names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The list of domain names for enabling SSO in Prefect Cloud.
        """
        return pulumi.get(self, "domain_names")

    @_builtins.property
    @pulumi.getter
    def handle(self) -> pulumi.Output[_builtins.str]:
        """
        Unique handle of the account
        """
        return pulumi.get(self, "handle")

    @_builtins.property
    @pulumi.getter
    def link(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        An optional for an external url associated with the account, e.g. https://prefect.io/
        """
        return pulumi.get(self, "link")

    @_builtins.property
    @pulumi.getter
    def location(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        An optional physical location for the account, e.g. Washington, D.C.
        """
        return pulumi.get(self, "location")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the account
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def settings(self) -> pulumi.Output['outputs.AccountSettings']:
        """
        Group of settings related to accounts
        """
        return pulumi.get(self, "settings")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

