# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['BlockArgs', 'Block']

@pulumi.input_type
class BlockArgs:
    def __init__(__self__, *,
                 type_slug: pulumi.Input[_builtins.str],
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 data: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo_version: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Block resource.

        :param pulumi.Input[_builtins.str] type_slug: Block Type slug, which determines the schema of the <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`">`data`</span> JSON attribute. Use `prefect block type ls` to view all available Block type slugs.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[_builtins.str] data: The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.str] data_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.float] data_wo_version: The version of the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute. This is used to track changes to the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute and trigger updates when the value changes.
        :param pulumi.Input[_builtins.str] name: Unique name of the Block
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        pulumi.set(__self__, "type_slug", type_slug)
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if data is not None:
            pulumi.set(__self__, "data", data)
        if data_wo is not None:
            pulumi.set(__self__, "data_wo", data_wo)
        if data_wo_version is not None:
            pulumi.set(__self__, "data_wo_version", data_wo_version)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="typeSlug")
    def type_slug(self) -> pulumi.Input[_builtins.str]:
        """
        Block Type slug, which determines the schema of the <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`">`data`</span> JSON attribute. Use `prefect block type ls` to view all available Block type slugs.
        """
        return pulumi.get(self, "type_slug")

    @type_slug.setter
    def type_slug(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type_slug", value)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID) where the Block is located
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        """
        return pulumi.get(self, "data")

    @data.setter
    def data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "data", value)

    @_builtins.property
    @pulumi.getter(name="dataWo")
    def data_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        """
        return pulumi.get(self, "data_wo")

    @data_wo.setter
    def data_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "data_wo", value)

    @_builtins.property
    @pulumi.getter(name="dataWoVersion")
    def data_wo_version(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The version of the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute. This is used to track changes to the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute and trigger updates when the value changes.
        """
        return pulumi.get(self, "data_wo_version")

    @data_wo_version.setter
    def data_wo_version(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "data_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unique name of the Block
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.input_type
class _BlockState:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 created: Optional[pulumi.Input[_builtins.str]] = None,
                 data: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo_version: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 type_slug: Optional[pulumi.Input[_builtins.str]] = None,
                 updated: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Block resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] data: The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.str] data_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.float] data_wo_version: The version of the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute. This is used to track changes to the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute and trigger updates when the value changes.
        :param pulumi.Input[_builtins.str] name: Unique name of the Block
        :param pulumi.Input[_builtins.str] type_slug: Block Type slug, which determines the schema of the <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`">`data`</span> JSON attribute. Use `prefect block type ls` to view all available Block type slugs.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if created is not None:
            pulumi.set(__self__, "created", created)
        if data is not None:
            pulumi.set(__self__, "data", data)
        if data_wo is not None:
            pulumi.set(__self__, "data_wo", data_wo)
        if data_wo_version is not None:
            pulumi.set(__self__, "data_wo_version", data_wo_version)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if type_slug is not None:
            pulumi.set(__self__, "type_slug", type_slug)
        if updated is not None:
            pulumi.set(__self__, "updated", updated)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID) where the Block is located
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        """
        return pulumi.get(self, "data")

    @data.setter
    def data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "data", value)

    @_builtins.property
    @pulumi.getter(name="dataWo")
    def data_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        """
        return pulumi.get(self, "data_wo")

    @data_wo.setter
    def data_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "data_wo", value)

    @_builtins.property
    @pulumi.getter(name="dataWoVersion")
    def data_wo_version(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The version of the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute. This is used to track changes to the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute and trigger updates when the value changes.
        """
        return pulumi.get(self, "data_wo_version")

    @data_wo_version.setter
    def data_wo_version(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "data_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unique name of the Block
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="typeSlug")
    def type_slug(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Block Type slug, which determines the schema of the <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`">`data`</span> JSON attribute. Use `prefect block type ls` to view all available Block type slugs.
        """
        return pulumi.get(self, "type_slug")

    @type_slug.setter
    def type_slug(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type_slug", value)

    @_builtins.property
    @pulumi.getter
    def updated(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @updated.setter
    def updated(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.type_token("prefect:index/block:Block")
class Block(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 data: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo_version: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 type_slug: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Block resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[_builtins.str] data: The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.str] data_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.float] data_wo_version: The version of the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute. This is used to track changes to the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute and trigger updates when the value changes.
        :param pulumi.Input[_builtins.str] name: Unique name of the Block
        :param pulumi.Input[_builtins.str] type_slug: Block Type slug, which determines the schema of the <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`">`data`</span> JSON attribute. Use `prefect block type ls` to view all available Block type slugs.
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: BlockArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Block resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param BlockArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BlockArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 data: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 data_wo_version: Optional[pulumi.Input[_builtins.float]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 type_slug: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BlockArgs.__new__(BlockArgs)

            __props__.__dict__["account_id"] = account_id
            __props__.__dict__["data"] = None if data is None else pulumi.Output.secret(data)
            __props__.__dict__["data_wo"] = None if data_wo is None else pulumi.Output.secret(data_wo)
            __props__.__dict__["data_wo_version"] = data_wo_version
            __props__.__dict__["name"] = name
            if type_slug is None and not opts.urn:
                raise TypeError("Missing required property 'type_slug'")
            __props__.__dict__["type_slug"] = type_slug
            __props__.__dict__["workspace_id"] = workspace_id
            __props__.__dict__["created"] = None
            __props__.__dict__["updated"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["data", "dataWo"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Block, __self__).__init__(
            'prefect:index/block:Block',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: Optional[pulumi.Input[_builtins.str]] = None,
            created: Optional[pulumi.Input[_builtins.str]] = None,
            data: Optional[pulumi.Input[_builtins.str]] = None,
            data_wo: Optional[pulumi.Input[_builtins.str]] = None,
            data_wo_version: Optional[pulumi.Input[_builtins.float]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            type_slug: Optional[pulumi.Input[_builtins.str]] = None,
            updated: Optional[pulumi.Input[_builtins.str]] = None,
            workspace_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'Block':
        """
        Get an existing Block resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] data: The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.str] data_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        :param pulumi.Input[_builtins.float] data_wo_version: The version of the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute. This is used to track changes to the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute and trigger updates when the value changes.
        :param pulumi.Input[_builtins.str] name: Unique name of the Block
        :param pulumi.Input[_builtins.str] type_slug: Block Type slug, which determines the schema of the <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`">`data`</span> JSON attribute. Use `prefect block type ls` to view all available Block type slugs.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _BlockState.__new__(_BlockState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["created"] = created
        __props__.__dict__["data"] = data
        __props__.__dict__["data_wo"] = data_wo
        __props__.__dict__["data_wo_version"] = data_wo_version
        __props__.__dict__["name"] = name
        __props__.__dict__["type_slug"] = type_slug
        __props__.__dict__["updated"] = updated
        __props__.__dict__["workspace_id"] = workspace_id
        return Block(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Account ID (UUID) where the Block is located
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def data(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter(name="dataWo")
    def data_wo(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        The user-inputted Block payload, as a JSON string. Use <span pulumi-lang-nodejs="`jsonencode`" pulumi-lang-dotnet="`Jsonencode`" pulumi-lang-go="`jsonencode`" pulumi-lang-python="`jsonencode`" pulumi-lang-yaml="`jsonencode`" pulumi-lang-java="`jsonencode`">`jsonencode`</span> on the provided value to satisfy the underlying JSON type. The value's schema will depend on the selected <span pulumi-lang-nodejs="`type`" pulumi-lang-dotnet="`Type`" pulumi-lang-go="`type`" pulumi-lang-python="`type`" pulumi-lang-yaml="`type`" pulumi-lang-java="`type`">`type`</span> slug. Use `prefect block type inspect <slug>` to view the data schema for a given Block type.
        """
        return pulumi.get(self, "data_wo")

    @_builtins.property
    @pulumi.getter(name="dataWoVersion")
    def data_wo_version(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The version of the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute. This is used to track changes to the <span pulumi-lang-nodejs="`dataWo`" pulumi-lang-dotnet="`DataWo`" pulumi-lang-go="`dataWo`" pulumi-lang-python="`data_wo`" pulumi-lang-yaml="`dataWo`" pulumi-lang-java="`dataWo`">`data_wo`</span> attribute and trigger updates when the value changes.
        """
        return pulumi.get(self, "data_wo_version")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Unique name of the Block
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="typeSlug")
    def type_slug(self) -> pulumi.Output[_builtins.str]:
        """
        Block Type slug, which determines the schema of the <span pulumi-lang-nodejs="`data`" pulumi-lang-dotnet="`Data`" pulumi-lang-go="`data`" pulumi-lang-python="`data`" pulumi-lang-yaml="`data`" pulumi-lang-java="`data`">`data`</span> JSON attribute. Use `prefect block type ls` to view all available Block type slugs.
        """
        return pulumi.get(self, "type_slug")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

