# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['BlockSchemaArgs', 'BlockSchema']

@pulumi.input_type
class BlockSchemaArgs:
    def __init__(__self__, *,
                 block_type_id: pulumi.Input[_builtins.str],
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 fields: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a BlockSchema resource.

        :param pulumi.Input[_builtins.str] block_type_id: The ID of the block type.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: The capabilities of the block schema.
        :param pulumi.Input[_builtins.str] fields: The fields of the block schema.
        :param pulumi.Input[_builtins.str] version: The version of the block schema.
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        pulumi.set(__self__, "block_type_id", block_type_id)
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if capabilities is not None:
            pulumi.set(__self__, "capabilities", capabilities)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if version is not None:
            pulumi.set(__self__, "version", version)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="blockTypeId")
    def block_type_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the block type.
        """
        return pulumi.get(self, "block_type_id")

    @block_type_id.setter
    def block_type_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "block_type_id", value)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID) where the Block is located
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The capabilities of the block schema.
        """
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter
    def fields(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The fields of the block schema.
        """
        return pulumi.get(self, "fields")

    @fields.setter
    def fields(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "fields", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the block schema.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.input_type
class _BlockSchemaState:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 block_type: Optional[pulumi.Input[_builtins.str]] = None,
                 block_type_id: Optional[pulumi.Input[_builtins.str]] = None,
                 capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 checksum: Optional[pulumi.Input[_builtins.str]] = None,
                 created: Optional[pulumi.Input[_builtins.str]] = None,
                 fields: Optional[pulumi.Input[_builtins.str]] = None,
                 updated: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering BlockSchema resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[_builtins.str] block_type: The type of the block.
        :param pulumi.Input[_builtins.str] block_type_id: The ID of the block type.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: The capabilities of the block schema.
        :param pulumi.Input[_builtins.str] checksum: The checksum of the block schema.
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] fields: The fields of the block schema.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] version: The version of the block schema.
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if block_type is not None:
            pulumi.set(__self__, "block_type", block_type)
        if block_type_id is not None:
            pulumi.set(__self__, "block_type_id", block_type_id)
        if capabilities is not None:
            pulumi.set(__self__, "capabilities", capabilities)
        if checksum is not None:
            pulumi.set(__self__, "checksum", checksum)
        if created is not None:
            pulumi.set(__self__, "created", created)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if updated is not None:
            pulumi.set(__self__, "updated", updated)
        if version is not None:
            pulumi.set(__self__, "version", version)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID) where the Block is located
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="blockType")
    def block_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The type of the block.
        """
        return pulumi.get(self, "block_type")

    @block_type.setter
    def block_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "block_type", value)

    @_builtins.property
    @pulumi.getter(name="blockTypeId")
    def block_type_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the block type.
        """
        return pulumi.get(self, "block_type_id")

    @block_type_id.setter
    def block_type_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "block_type_id", value)

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The capabilities of the block schema.
        """
        return pulumi.get(self, "capabilities")

    @capabilities.setter
    def capabilities(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "capabilities", value)

    @_builtins.property
    @pulumi.getter
    def checksum(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The checksum of the block schema.
        """
        return pulumi.get(self, "checksum")

    @checksum.setter
    def checksum(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "checksum", value)

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter
    def fields(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The fields of the block schema.
        """
        return pulumi.get(self, "fields")

    @fields.setter
    def fields(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "fields", value)

    @_builtins.property
    @pulumi.getter
    def updated(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @updated.setter
    def updated(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the block schema.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.type_token("prefect:index/blockSchema:BlockSchema")
class BlockSchema(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 block_type_id: Optional[pulumi.Input[_builtins.str]] = None,
                 capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 fields: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a BlockSchema resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[_builtins.str] block_type_id: The ID of the block type.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: The capabilities of the block schema.
        :param pulumi.Input[_builtins.str] fields: The fields of the block schema.
        :param pulumi.Input[_builtins.str] version: The version of the block schema.
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: BlockSchemaArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a BlockSchema resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param BlockSchemaArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BlockSchemaArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 block_type_id: Optional[pulumi.Input[_builtins.str]] = None,
                 capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 fields: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BlockSchemaArgs.__new__(BlockSchemaArgs)

            __props__.__dict__["account_id"] = account_id
            if block_type_id is None and not opts.urn:
                raise TypeError("Missing required property 'block_type_id'")
            __props__.__dict__["block_type_id"] = block_type_id
            __props__.__dict__["capabilities"] = capabilities
            __props__.__dict__["fields"] = fields
            __props__.__dict__["version"] = version
            __props__.__dict__["workspace_id"] = workspace_id
            __props__.__dict__["block_type"] = None
            __props__.__dict__["checksum"] = None
            __props__.__dict__["created"] = None
            __props__.__dict__["updated"] = None
        super(BlockSchema, __self__).__init__(
            'prefect:index/blockSchema:BlockSchema',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: Optional[pulumi.Input[_builtins.str]] = None,
            block_type: Optional[pulumi.Input[_builtins.str]] = None,
            block_type_id: Optional[pulumi.Input[_builtins.str]] = None,
            capabilities: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            checksum: Optional[pulumi.Input[_builtins.str]] = None,
            created: Optional[pulumi.Input[_builtins.str]] = None,
            fields: Optional[pulumi.Input[_builtins.str]] = None,
            updated: Optional[pulumi.Input[_builtins.str]] = None,
            version: Optional[pulumi.Input[_builtins.str]] = None,
            workspace_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'BlockSchema':
        """
        Get an existing BlockSchema resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the Block is located
        :param pulumi.Input[_builtins.str] block_type: The type of the block.
        :param pulumi.Input[_builtins.str] block_type_id: The ID of the block type.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] capabilities: The capabilities of the block schema.
        :param pulumi.Input[_builtins.str] checksum: The checksum of the block schema.
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] fields: The fields of the block schema.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] version: The version of the block schema.
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _BlockSchemaState.__new__(_BlockSchemaState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["block_type"] = block_type
        __props__.__dict__["block_type_id"] = block_type_id
        __props__.__dict__["capabilities"] = capabilities
        __props__.__dict__["checksum"] = checksum
        __props__.__dict__["created"] = created
        __props__.__dict__["fields"] = fields
        __props__.__dict__["updated"] = updated
        __props__.__dict__["version"] = version
        __props__.__dict__["workspace_id"] = workspace_id
        return BlockSchema(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Account ID (UUID) where the Block is located
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="blockType")
    def block_type(self) -> pulumi.Output[_builtins.str]:
        """
        The type of the block.
        """
        return pulumi.get(self, "block_type")

    @_builtins.property
    @pulumi.getter(name="blockTypeId")
    def block_type_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the block type.
        """
        return pulumi.get(self, "block_type_id")

    @_builtins.property
    @pulumi.getter
    def capabilities(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The capabilities of the block schema.
        """
        return pulumi.get(self, "capabilities")

    @_builtins.property
    @pulumi.getter
    def checksum(self) -> pulumi.Output[_builtins.str]:
        """
        The checksum of the block schema.
        """
        return pulumi.get(self, "checksum")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def fields(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The fields of the block schema.
        """
        return pulumi.get(self, "fields")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The version of the block schema.
        """
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Workspace ID (UUID) where the Block is located. In Prefect Cloud, either the <span pulumi-lang-nodejs="`prefect.Block`" pulumi-lang-dotnet="`prefect.Block`" pulumi-lang-go="`Block`" pulumi-lang-python="`Block`" pulumi-lang-yaml="`prefect.Block`" pulumi-lang-java="`prefect.Block`">`prefect.Block`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

