# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetWorkQueueResult',
    'AwaitableGetWorkQueueResult',
    'get_work_queue',
    'get_work_queue_output',
]

@pulumi.output_type
class GetWorkQueueResult:
    """
    A collection of values returned by getWorkQueue.
    """
    def __init__(__self__, account_id=None, concurrency_limit=None, created=None, description=None, id=None, is_paused=None, name=None, priority=None, updated=None, work_pool_name=None, workspace_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if concurrency_limit and not isinstance(concurrency_limit, float):
            raise TypeError("Expected argument 'concurrency_limit' to be a float")
        pulumi.set(__self__, "concurrency_limit", concurrency_limit)
        if created and not isinstance(created, str):
            raise TypeError("Expected argument 'created' to be a str")
        pulumi.set(__self__, "created", created)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if is_paused and not isinstance(is_paused, bool):
            raise TypeError("Expected argument 'is_paused' to be a bool")
        pulumi.set(__self__, "is_paused", is_paused)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if priority and not isinstance(priority, float):
            raise TypeError("Expected argument 'priority' to be a float")
        pulumi.set(__self__, "priority", priority)
        if updated and not isinstance(updated, str):
            raise TypeError("Expected argument 'updated' to be a str")
        pulumi.set(__self__, "updated", updated)
        if work_pool_name and not isinstance(work_pool_name, str):
            raise TypeError("Expected argument 'work_pool_name' to be a str")
        pulumi.set(__self__, "work_pool_name", work_pool_name)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> _builtins.float:
        return pulumi.get(self, "concurrency_limit")

    @_builtins.property
    @pulumi.getter
    def created(self) -> _builtins.str:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="isPaused")
    def is_paused(self) -> _builtins.bool:
        return pulumi.get(self, "is_paused")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def priority(self) -> _builtins.float:
        return pulumi.get(self, "priority")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> _builtins.str:
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter(name="workPoolName")
    def work_pool_name(self) -> _builtins.str:
        return pulumi.get(self, "work_pool_name")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "workspace_id")


class AwaitableGetWorkQueueResult(GetWorkQueueResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkQueueResult(
            account_id=self.account_id,
            concurrency_limit=self.concurrency_limit,
            created=self.created,
            description=self.description,
            id=self.id,
            is_paused=self.is_paused,
            name=self.name,
            priority=self.priority,
            updated=self.updated,
            work_pool_name=self.work_pool_name,
            workspace_id=self.workspace_id)


def get_work_queue(account_id: Optional[_builtins.str] = None,
                   concurrency_limit: Optional[_builtins.float] = None,
                   description: Optional[_builtins.str] = None,
                   id: Optional[_builtins.str] = None,
                   name: Optional[_builtins.str] = None,
                   work_pool_name: Optional[_builtins.str] = None,
                   workspace_id: Optional[_builtins.str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkQueueResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['concurrencyLimit'] = concurrency_limit
    __args__['description'] = description
    __args__['id'] = id
    __args__['name'] = name
    __args__['workPoolName'] = work_pool_name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getWorkQueue:getWorkQueue', __args__, opts=opts, typ=GetWorkQueueResult, package_ref=_utilities.get_package()).value

    return AwaitableGetWorkQueueResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        concurrency_limit=pulumi.get(__ret__, 'concurrency_limit'),
        created=pulumi.get(__ret__, 'created'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        is_paused=pulumi.get(__ret__, 'is_paused'),
        name=pulumi.get(__ret__, 'name'),
        priority=pulumi.get(__ret__, 'priority'),
        updated=pulumi.get(__ret__, 'updated'),
        work_pool_name=pulumi.get(__ret__, 'work_pool_name'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_work_queue_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          concurrency_limit: Optional[pulumi.Input[Optional[_builtins.float]]] = None,
                          description: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          work_pool_name: Optional[pulumi.Input[_builtins.str]] = None,
                          workspace_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetWorkQueueResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['concurrencyLimit'] = concurrency_limit
    __args__['description'] = description
    __args__['id'] = id
    __args__['name'] = name
    __args__['workPoolName'] = work_pool_name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getWorkQueue:getWorkQueue', __args__, opts=opts, typ=GetWorkQueueResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetWorkQueueResult(
        account_id=pulumi.get(__response__, 'account_id'),
        concurrency_limit=pulumi.get(__response__, 'concurrency_limit'),
        created=pulumi.get(__response__, 'created'),
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        is_paused=pulumi.get(__response__, 'is_paused'),
        name=pulumi.get(__response__, 'name'),
        priority=pulumi.get(__response__, 'priority'),
        updated=pulumi.get(__response__, 'updated'),
        work_pool_name=pulumi.get(__response__, 'work_pool_name'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
