# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetWorkPoolResult',
    'AwaitableGetWorkPoolResult',
    'get_work_pool',
    'get_work_pool_output',
]

@pulumi.output_type
class GetWorkPoolResult:
    """
    A collection of values returned by getWorkPool.
    """
    def __init__(__self__, account_id=None, base_job_template=None, concurrency_limit=None, created=None, default_queue_id=None, description=None, id=None, name=None, paused=None, type=None, updated=None, workspace_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if base_job_template and not isinstance(base_job_template, str):
            raise TypeError("Expected argument 'base_job_template' to be a str")
        pulumi.set(__self__, "base_job_template", base_job_template)
        if concurrency_limit and not isinstance(concurrency_limit, float):
            raise TypeError("Expected argument 'concurrency_limit' to be a float")
        pulumi.set(__self__, "concurrency_limit", concurrency_limit)
        if created and not isinstance(created, str):
            raise TypeError("Expected argument 'created' to be a str")
        pulumi.set(__self__, "created", created)
        if default_queue_id and not isinstance(default_queue_id, str):
            raise TypeError("Expected argument 'default_queue_id' to be a str")
        pulumi.set(__self__, "default_queue_id", default_queue_id)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if paused and not isinstance(paused, bool):
            raise TypeError("Expected argument 'paused' to be a bool")
        pulumi.set(__self__, "paused", paused)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if updated and not isinstance(updated, str):
            raise TypeError("Expected argument 'updated' to be a str")
        pulumi.set(__self__, "updated", updated)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="baseJobTemplate")
    def base_job_template(self) -> _builtins.str:
        return pulumi.get(self, "base_job_template")

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> _builtins.float:
        return pulumi.get(self, "concurrency_limit")

    @_builtins.property
    @pulumi.getter
    def created(self) -> _builtins.str:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter(name="defaultQueueId")
    def default_queue_id(self) -> _builtins.str:
        return pulumi.get(self, "default_queue_id")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def paused(self) -> _builtins.bool:
        return pulumi.get(self, "paused")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> _builtins.str:
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "workspace_id")


class AwaitableGetWorkPoolResult(GetWorkPoolResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkPoolResult(
            account_id=self.account_id,
            base_job_template=self.base_job_template,
            concurrency_limit=self.concurrency_limit,
            created=self.created,
            default_queue_id=self.default_queue_id,
            description=self.description,
            id=self.id,
            name=self.name,
            paused=self.paused,
            type=self.type,
            updated=self.updated,
            workspace_id=self.workspace_id)


def get_work_pool(account_id: Optional[_builtins.str] = None,
                  concurrency_limit: Optional[_builtins.float] = None,
                  default_queue_id: Optional[_builtins.str] = None,
                  description: Optional[_builtins.str] = None,
                  id: Optional[_builtins.str] = None,
                  name: Optional[_builtins.str] = None,
                  workspace_id: Optional[_builtins.str] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkPoolResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['concurrencyLimit'] = concurrency_limit
    __args__['defaultQueueId'] = default_queue_id
    __args__['description'] = description
    __args__['id'] = id
    __args__['name'] = name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getWorkPool:getWorkPool', __args__, opts=opts, typ=GetWorkPoolResult, package_ref=_utilities.get_package()).value

    return AwaitableGetWorkPoolResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        base_job_template=pulumi.get(__ret__, 'base_job_template'),
        concurrency_limit=pulumi.get(__ret__, 'concurrency_limit'),
        created=pulumi.get(__ret__, 'created'),
        default_queue_id=pulumi.get(__ret__, 'default_queue_id'),
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        paused=pulumi.get(__ret__, 'paused'),
        type=pulumi.get(__ret__, 'type'),
        updated=pulumi.get(__ret__, 'updated'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_work_pool_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         concurrency_limit: Optional[pulumi.Input[Optional[_builtins.float]]] = None,
                         default_queue_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         description: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         workspace_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetWorkPoolResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['concurrencyLimit'] = concurrency_limit
    __args__['defaultQueueId'] = default_queue_id
    __args__['description'] = description
    __args__['id'] = id
    __args__['name'] = name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getWorkPool:getWorkPool', __args__, opts=opts, typ=GetWorkPoolResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetWorkPoolResult(
        account_id=pulumi.get(__response__, 'account_id'),
        base_job_template=pulumi.get(__response__, 'base_job_template'),
        concurrency_limit=pulumi.get(__response__, 'concurrency_limit'),
        created=pulumi.get(__response__, 'created'),
        default_queue_id=pulumi.get(__response__, 'default_queue_id'),
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        paused=pulumi.get(__response__, 'paused'),
        type=pulumi.get(__response__, 'type'),
        updated=pulumi.get(__response__, 'updated'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
