# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetAutomationResult',
    'AwaitableGetAutomationResult',
    'get_automation',
    'get_automation_output',
]

@pulumi.output_type
class GetAutomationResult:
    """
    A collection of values returned by getAutomation.
    """
    def __init__(__self__, account_id=None, actions=None, actions_on_resolves=None, actions_on_triggers=None, created=None, description=None, enabled=None, id=None, name=None, trigger=None, updated=None, workspace_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if actions and not isinstance(actions, list):
            raise TypeError("Expected argument 'actions' to be a list")
        pulumi.set(__self__, "actions", actions)
        if actions_on_resolves and not isinstance(actions_on_resolves, list):
            raise TypeError("Expected argument 'actions_on_resolves' to be a list")
        pulumi.set(__self__, "actions_on_resolves", actions_on_resolves)
        if actions_on_triggers and not isinstance(actions_on_triggers, list):
            raise TypeError("Expected argument 'actions_on_triggers' to be a list")
        pulumi.set(__self__, "actions_on_triggers", actions_on_triggers)
        if created and not isinstance(created, str):
            raise TypeError("Expected argument 'created' to be a str")
        pulumi.set(__self__, "created", created)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if trigger and not isinstance(trigger, dict):
            raise TypeError("Expected argument 'trigger' to be a dict")
        pulumi.set(__self__, "trigger", trigger)
        if updated and not isinstance(updated, str):
            raise TypeError("Expected argument 'updated' to be a str")
        pulumi.set(__self__, "updated", updated)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter
    def actions(self) -> Sequence['outputs.GetAutomationActionResult']:
        return pulumi.get(self, "actions")

    @_builtins.property
    @pulumi.getter(name="actionsOnResolves")
    def actions_on_resolves(self) -> Sequence['outputs.GetAutomationActionsOnResolfResult']:
        return pulumi.get(self, "actions_on_resolves")

    @_builtins.property
    @pulumi.getter(name="actionsOnTriggers")
    def actions_on_triggers(self) -> Sequence['outputs.GetAutomationActionsOnTriggerResult']:
        return pulumi.get(self, "actions_on_triggers")

    @_builtins.property
    @pulumi.getter
    def created(self) -> _builtins.str:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def trigger(self) -> 'outputs.GetAutomationTriggerResult':
        return pulumi.get(self, "trigger")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> _builtins.str:
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "workspace_id")


class AwaitableGetAutomationResult(GetAutomationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAutomationResult(
            account_id=self.account_id,
            actions=self.actions,
            actions_on_resolves=self.actions_on_resolves,
            actions_on_triggers=self.actions_on_triggers,
            created=self.created,
            description=self.description,
            enabled=self.enabled,
            id=self.id,
            name=self.name,
            trigger=self.trigger,
            updated=self.updated,
            workspace_id=self.workspace_id)


def get_automation(account_id: Optional[_builtins.str] = None,
                   id: Optional[_builtins.str] = None,
                   workspace_id: Optional[_builtins.str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAutomationResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['id'] = id
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getAutomation:getAutomation', __args__, opts=opts, typ=GetAutomationResult, package_ref=_utilities.get_package()).value

    return AwaitableGetAutomationResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        actions=pulumi.get(__ret__, 'actions'),
        actions_on_resolves=pulumi.get(__ret__, 'actions_on_resolves'),
        actions_on_triggers=pulumi.get(__ret__, 'actions_on_triggers'),
        created=pulumi.get(__ret__, 'created'),
        description=pulumi.get(__ret__, 'description'),
        enabled=pulumi.get(__ret__, 'enabled'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        trigger=pulumi.get(__ret__, 'trigger'),
        updated=pulumi.get(__ret__, 'updated'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_automation_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          id: Optional[pulumi.Input[_builtins.str]] = None,
                          workspace_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAutomationResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['id'] = id
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getAutomation:getAutomation', __args__, opts=opts, typ=GetAutomationResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetAutomationResult(
        account_id=pulumi.get(__response__, 'account_id'),
        actions=pulumi.get(__response__, 'actions'),
        actions_on_resolves=pulumi.get(__response__, 'actions_on_resolves'),
        actions_on_triggers=pulumi.get(__response__, 'actions_on_triggers'),
        created=pulumi.get(__response__, 'created'),
        description=pulumi.get(__response__, 'description'),
        enabled=pulumi.get(__response__, 'enabled'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        trigger=pulumi.get(__response__, 'trigger'),
        updated=pulumi.get(__response__, 'updated'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
