# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetWorkerMetadataResult',
    'AwaitableGetWorkerMetadataResult',
    'get_worker_metadata',
    'get_worker_metadata_output',
]

@pulumi.output_type
class GetWorkerMetadataResult:
    """
    A collection of values returned by getWorkerMetadata.
    """
    def __init__(__self__, account_id=None, base_job_configs=None, id=None, workspace_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if base_job_configs and not isinstance(base_job_configs, dict):
            raise TypeError("Expected argument 'base_job_configs' to be a dict")
        pulumi.set(__self__, "base_job_configs", base_job_configs)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="baseJobConfigs")
    def base_job_configs(self) -> 'outputs.GetWorkerMetadataBaseJobConfigsResult':
        return pulumi.get(self, "base_job_configs")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "workspace_id")


class AwaitableGetWorkerMetadataResult(GetWorkerMetadataResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkerMetadataResult(
            account_id=self.account_id,
            base_job_configs=self.base_job_configs,
            id=self.id,
            workspace_id=self.workspace_id)


def get_worker_metadata(account_id: Optional[_builtins.str] = None,
                        workspace_id: Optional[_builtins.str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkerMetadataResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getWorkerMetadata:getWorkerMetadata', __args__, opts=opts, typ=GetWorkerMetadataResult, package_ref=_utilities.get_package()).value

    return AwaitableGetWorkerMetadataResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        base_job_configs=pulumi.get(__ret__, 'base_job_configs'),
        id=pulumi.get(__ret__, 'id'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_worker_metadata_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               workspace_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetWorkerMetadataResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getWorkerMetadata:getWorkerMetadata', __args__, opts=opts, typ=GetWorkerMetadataResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetWorkerMetadataResult(
        account_id=pulumi.get(__response__, 'account_id'),
        base_job_configs=pulumi.get(__response__, 'base_job_configs'),
        id=pulumi.get(__response__, 'id'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
