# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetAccountMemberResult',
    'AwaitableGetAccountMemberResult',
    'get_account_member',
    'get_account_member_output',
]

@pulumi.output_type
class GetAccountMemberResult:
    """
    A collection of values returned by getAccountMember.
    """
    def __init__(__self__, account_id=None, account_role_id=None, account_role_name=None, actor_id=None, email=None, first_name=None, handle=None, id=None, last_name=None, user_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if account_role_id and not isinstance(account_role_id, str):
            raise TypeError("Expected argument 'account_role_id' to be a str")
        pulumi.set(__self__, "account_role_id", account_role_id)
        if account_role_name and not isinstance(account_role_name, str):
            raise TypeError("Expected argument 'account_role_name' to be a str")
        pulumi.set(__self__, "account_role_name", account_role_name)
        if actor_id and not isinstance(actor_id, str):
            raise TypeError("Expected argument 'actor_id' to be a str")
        pulumi.set(__self__, "actor_id", actor_id)
        if email and not isinstance(email, str):
            raise TypeError("Expected argument 'email' to be a str")
        pulumi.set(__self__, "email", email)
        if first_name and not isinstance(first_name, str):
            raise TypeError("Expected argument 'first_name' to be a str")
        pulumi.set(__self__, "first_name", first_name)
        if handle and not isinstance(handle, str):
            raise TypeError("Expected argument 'handle' to be a str")
        pulumi.set(__self__, "handle", handle)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if last_name and not isinstance(last_name, str):
            raise TypeError("Expected argument 'last_name' to be a str")
        pulumi.set(__self__, "last_name", last_name)
        if user_id and not isinstance(user_id, str):
            raise TypeError("Expected argument 'user_id' to be a str")
        pulumi.set(__self__, "user_id", user_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="accountRoleId")
    def account_role_id(self) -> _builtins.str:
        return pulumi.get(self, "account_role_id")

    @_builtins.property
    @pulumi.getter(name="accountRoleName")
    def account_role_name(self) -> _builtins.str:
        return pulumi.get(self, "account_role_name")

    @_builtins.property
    @pulumi.getter(name="actorId")
    def actor_id(self) -> _builtins.str:
        return pulumi.get(self, "actor_id")

    @_builtins.property
    @pulumi.getter
    def email(self) -> _builtins.str:
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter(name="firstName")
    def first_name(self) -> _builtins.str:
        return pulumi.get(self, "first_name")

    @_builtins.property
    @pulumi.getter
    def handle(self) -> _builtins.str:
        return pulumi.get(self, "handle")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="lastName")
    def last_name(self) -> _builtins.str:
        return pulumi.get(self, "last_name")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> _builtins.str:
        return pulumi.get(self, "user_id")


class AwaitableGetAccountMemberResult(GetAccountMemberResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAccountMemberResult(
            account_id=self.account_id,
            account_role_id=self.account_role_id,
            account_role_name=self.account_role_name,
            actor_id=self.actor_id,
            email=self.email,
            first_name=self.first_name,
            handle=self.handle,
            id=self.id,
            last_name=self.last_name,
            user_id=self.user_id)


def get_account_member(account_id: Optional[_builtins.str] = None,
                       email: Optional[_builtins.str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAccountMemberResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['email'] = email
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getAccountMember:getAccountMember', __args__, opts=opts, typ=GetAccountMemberResult, package_ref=_utilities.get_package()).value

    return AwaitableGetAccountMemberResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        account_role_id=pulumi.get(__ret__, 'account_role_id'),
        account_role_name=pulumi.get(__ret__, 'account_role_name'),
        actor_id=pulumi.get(__ret__, 'actor_id'),
        email=pulumi.get(__ret__, 'email'),
        first_name=pulumi.get(__ret__, 'first_name'),
        handle=pulumi.get(__ret__, 'handle'),
        id=pulumi.get(__ret__, 'id'),
        last_name=pulumi.get(__ret__, 'last_name'),
        user_id=pulumi.get(__ret__, 'user_id'))
def get_account_member_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                              email: Optional[pulumi.Input[_builtins.str]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAccountMemberResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['email'] = email
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getAccountMember:getAccountMember', __args__, opts=opts, typ=GetAccountMemberResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetAccountMemberResult(
        account_id=pulumi.get(__response__, 'account_id'),
        account_role_id=pulumi.get(__response__, 'account_role_id'),
        account_role_name=pulumi.get(__response__, 'account_role_name'),
        actor_id=pulumi.get(__response__, 'actor_id'),
        email=pulumi.get(__response__, 'email'),
        first_name=pulumi.get(__response__, 'first_name'),
        handle=pulumi.get(__response__, 'handle'),
        id=pulumi.get(__response__, 'id'),
        last_name=pulumi.get(__response__, 'last_name'),
        user_id=pulumi.get(__response__, 'user_id')))
