# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetGlobalConcurrencyLimitResult',
    'AwaitableGetGlobalConcurrencyLimitResult',
    'get_global_concurrency_limit',
    'get_global_concurrency_limit_output',
]

@pulumi.output_type
class GetGlobalConcurrencyLimitResult:
    """
    A collection of values returned by getGlobalConcurrencyLimit.
    """
    def __init__(__self__, account_id=None, active=None, active_slots=None, created=None, id=None, limit=None, name=None, slot_decay_per_second=None, updated=None, workspace_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if active and not isinstance(active, bool):
            raise TypeError("Expected argument 'active' to be a bool")
        pulumi.set(__self__, "active", active)
        if active_slots and not isinstance(active_slots, float):
            raise TypeError("Expected argument 'active_slots' to be a float")
        pulumi.set(__self__, "active_slots", active_slots)
        if created and not isinstance(created, str):
            raise TypeError("Expected argument 'created' to be a str")
        pulumi.set(__self__, "created", created)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if limit and not isinstance(limit, float):
            raise TypeError("Expected argument 'limit' to be a float")
        pulumi.set(__self__, "limit", limit)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if slot_decay_per_second and not isinstance(slot_decay_per_second, float):
            raise TypeError("Expected argument 'slot_decay_per_second' to be a float")
        pulumi.set(__self__, "slot_decay_per_second", slot_decay_per_second)
        if updated and not isinstance(updated, str):
            raise TypeError("Expected argument 'updated' to be a str")
        pulumi.set(__self__, "updated", updated)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> _builtins.str:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter
    def active(self) -> _builtins.bool:
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter(name="activeSlots")
    def active_slots(self) -> _builtins.float:
        return pulumi.get(self, "active_slots")

    @_builtins.property
    @pulumi.getter
    def created(self) -> _builtins.str:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> _builtins.float:
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="slotDecayPerSecond")
    def slot_decay_per_second(self) -> _builtins.float:
        return pulumi.get(self, "slot_decay_per_second")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> _builtins.str:
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> _builtins.str:
        return pulumi.get(self, "workspace_id")


class AwaitableGetGlobalConcurrencyLimitResult(GetGlobalConcurrencyLimitResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGlobalConcurrencyLimitResult(
            account_id=self.account_id,
            active=self.active,
            active_slots=self.active_slots,
            created=self.created,
            id=self.id,
            limit=self.limit,
            name=self.name,
            slot_decay_per_second=self.slot_decay_per_second,
            updated=self.updated,
            workspace_id=self.workspace_id)


def get_global_concurrency_limit(account_id: Optional[_builtins.str] = None,
                                 created: Optional[_builtins.str] = None,
                                 id: Optional[_builtins.str] = None,
                                 name: Optional[_builtins.str] = None,
                                 updated: Optional[_builtins.str] = None,
                                 workspace_id: Optional[_builtins.str] = None,
                                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGlobalConcurrencyLimitResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['created'] = created
    __args__['id'] = id
    __args__['name'] = name
    __args__['updated'] = updated
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getGlobalConcurrencyLimit:getGlobalConcurrencyLimit', __args__, opts=opts, typ=GetGlobalConcurrencyLimitResult, package_ref=_utilities.get_package()).value

    return AwaitableGetGlobalConcurrencyLimitResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        active=pulumi.get(__ret__, 'active'),
        active_slots=pulumi.get(__ret__, 'active_slots'),
        created=pulumi.get(__ret__, 'created'),
        id=pulumi.get(__ret__, 'id'),
        limit=pulumi.get(__ret__, 'limit'),
        name=pulumi.get(__ret__, 'name'),
        slot_decay_per_second=pulumi.get(__ret__, 'slot_decay_per_second'),
        updated=pulumi.get(__ret__, 'updated'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_global_concurrency_limit_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                        created: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                        id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                        name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                        updated: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                        workspace_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGlobalConcurrencyLimitResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['created'] = created
    __args__['id'] = id
    __args__['name'] = name
    __args__['updated'] = updated
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getGlobalConcurrencyLimit:getGlobalConcurrencyLimit', __args__, opts=opts, typ=GetGlobalConcurrencyLimitResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetGlobalConcurrencyLimitResult(
        account_id=pulumi.get(__response__, 'account_id'),
        active=pulumi.get(__response__, 'active'),
        active_slots=pulumi.get(__response__, 'active_slots'),
        created=pulumi.get(__response__, 'created'),
        id=pulumi.get(__response__, 'id'),
        limit=pulumi.get(__response__, 'limit'),
        name=pulumi.get(__response__, 'name'),
        slot_decay_per_second=pulumi.get(__response__, 'slot_decay_per_second'),
        updated=pulumi.get(__response__, 'updated'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
