# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetWorkQueuesResult',
    'AwaitableGetWorkQueuesResult',
    'get_work_queues',
    'get_work_queues_output',
]

@pulumi.output_type
class GetWorkQueuesResult:
    """
    A collection of values returned by getWorkQueues.
    """
    def __init__(__self__, account_id=None, filter_anies=None, id=None, work_pool_name=None, work_queues=None, workspace_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if filter_anies and not isinstance(filter_anies, list):
            raise TypeError("Expected argument 'filter_anies' to be a list")
        pulumi.set(__self__, "filter_anies", filter_anies)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if work_pool_name and not isinstance(work_pool_name, str):
            raise TypeError("Expected argument 'work_pool_name' to be a str")
        pulumi.set(__self__, "work_pool_name", work_pool_name)
        if work_queues and not isinstance(work_queues, list):
            raise TypeError("Expected argument 'work_queues' to be a list")
        pulumi.set(__self__, "work_queues", work_queues)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="filterAnies")
    def filter_anies(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "filter_anies")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="workPoolName")
    def work_pool_name(self) -> _builtins.str:
        return pulumi.get(self, "work_pool_name")

    @_builtins.property
    @pulumi.getter(name="workQueues")
    def work_queues(self) -> Sequence['outputs.GetWorkQueuesWorkQueueResult']:
        return pulumi.get(self, "work_queues")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "workspace_id")


class AwaitableGetWorkQueuesResult(GetWorkQueuesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetWorkQueuesResult(
            account_id=self.account_id,
            filter_anies=self.filter_anies,
            id=self.id,
            work_pool_name=self.work_pool_name,
            work_queues=self.work_queues,
            workspace_id=self.workspace_id)


def get_work_queues(account_id: Optional[_builtins.str] = None,
                    filter_anies: Optional[Sequence[_builtins.str]] = None,
                    work_pool_name: Optional[_builtins.str] = None,
                    workspace_id: Optional[_builtins.str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetWorkQueuesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['filterAnies'] = filter_anies
    __args__['workPoolName'] = work_pool_name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getWorkQueues:getWorkQueues', __args__, opts=opts, typ=GetWorkQueuesResult, package_ref=_utilities.get_package()).value

    return AwaitableGetWorkQueuesResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        filter_anies=pulumi.get(__ret__, 'filter_anies'),
        id=pulumi.get(__ret__, 'id'),
        work_pool_name=pulumi.get(__ret__, 'work_pool_name'),
        work_queues=pulumi.get(__ret__, 'work_queues'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_work_queues_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                           filter_anies: Optional[pulumi.Input[Optional[Sequence[_builtins.str]]]] = None,
                           work_pool_name: Optional[pulumi.Input[_builtins.str]] = None,
                           workspace_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetWorkQueuesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['filterAnies'] = filter_anies
    __args__['workPoolName'] = work_pool_name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getWorkQueues:getWorkQueues', __args__, opts=opts, typ=GetWorkQueuesResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetWorkQueuesResult(
        account_id=pulumi.get(__response__, 'account_id'),
        filter_anies=pulumi.get(__response__, 'filter_anies'),
        id=pulumi.get(__response__, 'id'),
        work_pool_name=pulumi.get(__response__, 'work_pool_name'),
        work_queues=pulumi.get(__response__, 'work_queues'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
