# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetDeploymentResult',
    'AwaitableGetDeploymentResult',
    'get_deployment',
    'get_deployment_output',
]

@pulumi.output_type
class GetDeploymentResult:
    """
    A collection of values returned by getDeployment.
    """
    def __init__(__self__, account_id=None, concurrency_limit=None, concurrency_options=None, created=None, description=None, enforce_parameter_schema=None, entrypoint=None, flow_id=None, flow_name=None, global_concurrency_limit_id=None, id=None, job_variables=None, name=None, parameter_openapi_schema=None, parameters=None, path=None, paused=None, pull_steps=None, storage_document_id=None, tags=None, updated=None, version=None, work_pool_name=None, work_queue_name=None, workspace_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if concurrency_limit and not isinstance(concurrency_limit, float):
            raise TypeError("Expected argument 'concurrency_limit' to be a float")
        pulumi.set(__self__, "concurrency_limit", concurrency_limit)
        if concurrency_options and not isinstance(concurrency_options, dict):
            raise TypeError("Expected argument 'concurrency_options' to be a dict")
        pulumi.set(__self__, "concurrency_options", concurrency_options)
        if created and not isinstance(created, str):
            raise TypeError("Expected argument 'created' to be a str")
        pulumi.set(__self__, "created", created)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if enforce_parameter_schema and not isinstance(enforce_parameter_schema, bool):
            raise TypeError("Expected argument 'enforce_parameter_schema' to be a bool")
        pulumi.set(__self__, "enforce_parameter_schema", enforce_parameter_schema)
        if entrypoint and not isinstance(entrypoint, str):
            raise TypeError("Expected argument 'entrypoint' to be a str")
        pulumi.set(__self__, "entrypoint", entrypoint)
        if flow_id and not isinstance(flow_id, str):
            raise TypeError("Expected argument 'flow_id' to be a str")
        pulumi.set(__self__, "flow_id", flow_id)
        if flow_name and not isinstance(flow_name, str):
            raise TypeError("Expected argument 'flow_name' to be a str")
        pulumi.set(__self__, "flow_name", flow_name)
        if global_concurrency_limit_id and not isinstance(global_concurrency_limit_id, str):
            raise TypeError("Expected argument 'global_concurrency_limit_id' to be a str")
        pulumi.set(__self__, "global_concurrency_limit_id", global_concurrency_limit_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if job_variables and not isinstance(job_variables, str):
            raise TypeError("Expected argument 'job_variables' to be a str")
        pulumi.set(__self__, "job_variables", job_variables)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if parameter_openapi_schema and not isinstance(parameter_openapi_schema, str):
            raise TypeError("Expected argument 'parameter_openapi_schema' to be a str")
        pulumi.set(__self__, "parameter_openapi_schema", parameter_openapi_schema)
        if parameters and not isinstance(parameters, str):
            raise TypeError("Expected argument 'parameters' to be a str")
        pulumi.set(__self__, "parameters", parameters)
        if path and not isinstance(path, str):
            raise TypeError("Expected argument 'path' to be a str")
        pulumi.set(__self__, "path", path)
        if paused and not isinstance(paused, bool):
            raise TypeError("Expected argument 'paused' to be a bool")
        pulumi.set(__self__, "paused", paused)
        if pull_steps and not isinstance(pull_steps, list):
            raise TypeError("Expected argument 'pull_steps' to be a list")
        pulumi.set(__self__, "pull_steps", pull_steps)
        if storage_document_id and not isinstance(storage_document_id, str):
            raise TypeError("Expected argument 'storage_document_id' to be a str")
        pulumi.set(__self__, "storage_document_id", storage_document_id)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if updated and not isinstance(updated, str):
            raise TypeError("Expected argument 'updated' to be a str")
        pulumi.set(__self__, "updated", updated)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)
        if work_pool_name and not isinstance(work_pool_name, str):
            raise TypeError("Expected argument 'work_pool_name' to be a str")
        pulumi.set(__self__, "work_pool_name", work_pool_name)
        if work_queue_name and not isinstance(work_queue_name, str):
            raise TypeError("Expected argument 'work_queue_name' to be a str")
        pulumi.set(__self__, "work_queue_name", work_queue_name)
        if workspace_id and not isinstance(workspace_id, str):
            raise TypeError("Expected argument 'workspace_id' to be a str")
        pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> _builtins.str:
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> _builtins.float:
        return pulumi.get(self, "concurrency_limit")

    @_builtins.property
    @pulumi.getter(name="concurrencyOptions")
    def concurrency_options(self) -> 'outputs.GetDeploymentConcurrencyOptionsResult':
        return pulumi.get(self, "concurrency_options")

    @_builtins.property
    @pulumi.getter
    def created(self) -> _builtins.str:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="enforceParameterSchema")
    def enforce_parameter_schema(self) -> _builtins.bool:
        return pulumi.get(self, "enforce_parameter_schema")

    @_builtins.property
    @pulumi.getter
    def entrypoint(self) -> _builtins.str:
        return pulumi.get(self, "entrypoint")

    @_builtins.property
    @pulumi.getter(name="flowId")
    def flow_id(self) -> _builtins.str:
        return pulumi.get(self, "flow_id")

    @_builtins.property
    @pulumi.getter(name="flowName")
    def flow_name(self) -> _builtins.str:
        return pulumi.get(self, "flow_name")

    @_builtins.property
    @pulumi.getter(name="globalConcurrencyLimitId")
    def global_concurrency_limit_id(self) -> _builtins.str:
        return pulumi.get(self, "global_concurrency_limit_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="jobVariables")
    def job_variables(self) -> _builtins.str:
        return pulumi.get(self, "job_variables")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="parameterOpenapiSchema")
    def parameter_openapi_schema(self) -> _builtins.str:
        return pulumi.get(self, "parameter_openapi_schema")

    @_builtins.property
    @pulumi.getter
    def parameters(self) -> _builtins.str:
        return pulumi.get(self, "parameters")

    @_builtins.property
    @pulumi.getter
    def path(self) -> _builtins.str:
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def paused(self) -> _builtins.bool:
        return pulumi.get(self, "paused")

    @_builtins.property
    @pulumi.getter(name="pullSteps")
    def pull_steps(self) -> Sequence['outputs.GetDeploymentPullStepResult']:
        return pulumi.get(self, "pull_steps")

    @_builtins.property
    @pulumi.getter(name="storageDocumentId")
    def storage_document_id(self) -> _builtins.str:
        return pulumi.get(self, "storage_document_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> _builtins.str:
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter(name="workPoolName")
    def work_pool_name(self) -> _builtins.str:
        return pulumi.get(self, "work_pool_name")

    @_builtins.property
    @pulumi.getter(name="workQueueName")
    def work_queue_name(self) -> _builtins.str:
        return pulumi.get(self, "work_queue_name")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> _builtins.str:
        return pulumi.get(self, "workspace_id")


class AwaitableGetDeploymentResult(GetDeploymentResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDeploymentResult(
            account_id=self.account_id,
            concurrency_limit=self.concurrency_limit,
            concurrency_options=self.concurrency_options,
            created=self.created,
            description=self.description,
            enforce_parameter_schema=self.enforce_parameter_schema,
            entrypoint=self.entrypoint,
            flow_id=self.flow_id,
            flow_name=self.flow_name,
            global_concurrency_limit_id=self.global_concurrency_limit_id,
            id=self.id,
            job_variables=self.job_variables,
            name=self.name,
            parameter_openapi_schema=self.parameter_openapi_schema,
            parameters=self.parameters,
            path=self.path,
            paused=self.paused,
            pull_steps=self.pull_steps,
            storage_document_id=self.storage_document_id,
            tags=self.tags,
            updated=self.updated,
            version=self.version,
            work_pool_name=self.work_pool_name,
            work_queue_name=self.work_queue_name,
            workspace_id=self.workspace_id)


def get_deployment(account_id: Optional[_builtins.str] = None,
                   flow_name: Optional[_builtins.str] = None,
                   id: Optional[_builtins.str] = None,
                   name: Optional[_builtins.str] = None,
                   workspace_id: Optional[_builtins.str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDeploymentResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['flowName'] = flow_name
    __args__['id'] = id
    __args__['name'] = name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('prefect:index/getDeployment:getDeployment', __args__, opts=opts, typ=GetDeploymentResult, package_ref=_utilities.get_package()).value

    return AwaitableGetDeploymentResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        concurrency_limit=pulumi.get(__ret__, 'concurrency_limit'),
        concurrency_options=pulumi.get(__ret__, 'concurrency_options'),
        created=pulumi.get(__ret__, 'created'),
        description=pulumi.get(__ret__, 'description'),
        enforce_parameter_schema=pulumi.get(__ret__, 'enforce_parameter_schema'),
        entrypoint=pulumi.get(__ret__, 'entrypoint'),
        flow_id=pulumi.get(__ret__, 'flow_id'),
        flow_name=pulumi.get(__ret__, 'flow_name'),
        global_concurrency_limit_id=pulumi.get(__ret__, 'global_concurrency_limit_id'),
        id=pulumi.get(__ret__, 'id'),
        job_variables=pulumi.get(__ret__, 'job_variables'),
        name=pulumi.get(__ret__, 'name'),
        parameter_openapi_schema=pulumi.get(__ret__, 'parameter_openapi_schema'),
        parameters=pulumi.get(__ret__, 'parameters'),
        path=pulumi.get(__ret__, 'path'),
        paused=pulumi.get(__ret__, 'paused'),
        pull_steps=pulumi.get(__ret__, 'pull_steps'),
        storage_document_id=pulumi.get(__ret__, 'storage_document_id'),
        tags=pulumi.get(__ret__, 'tags'),
        updated=pulumi.get(__ret__, 'updated'),
        version=pulumi.get(__ret__, 'version'),
        work_pool_name=pulumi.get(__ret__, 'work_pool_name'),
        work_queue_name=pulumi.get(__ret__, 'work_queue_name'),
        workspace_id=pulumi.get(__ret__, 'workspace_id'))
def get_deployment_output(account_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          flow_name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          name: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          workspace_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDeploymentResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['flowName'] = flow_name
    __args__['id'] = id
    __args__['name'] = name
    __args__['workspaceId'] = workspace_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('prefect:index/getDeployment:getDeployment', __args__, opts=opts, typ=GetDeploymentResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetDeploymentResult(
        account_id=pulumi.get(__response__, 'account_id'),
        concurrency_limit=pulumi.get(__response__, 'concurrency_limit'),
        concurrency_options=pulumi.get(__response__, 'concurrency_options'),
        created=pulumi.get(__response__, 'created'),
        description=pulumi.get(__response__, 'description'),
        enforce_parameter_schema=pulumi.get(__response__, 'enforce_parameter_schema'),
        entrypoint=pulumi.get(__response__, 'entrypoint'),
        flow_id=pulumi.get(__response__, 'flow_id'),
        flow_name=pulumi.get(__response__, 'flow_name'),
        global_concurrency_limit_id=pulumi.get(__response__, 'global_concurrency_limit_id'),
        id=pulumi.get(__response__, 'id'),
        job_variables=pulumi.get(__response__, 'job_variables'),
        name=pulumi.get(__response__, 'name'),
        parameter_openapi_schema=pulumi.get(__response__, 'parameter_openapi_schema'),
        parameters=pulumi.get(__response__, 'parameters'),
        path=pulumi.get(__response__, 'path'),
        paused=pulumi.get(__response__, 'paused'),
        pull_steps=pulumi.get(__response__, 'pull_steps'),
        storage_document_id=pulumi.get(__response__, 'storage_document_id'),
        tags=pulumi.get(__response__, 'tags'),
        updated=pulumi.get(__response__, 'updated'),
        version=pulumi.get(__response__, 'version'),
        work_pool_name=pulumi.get(__response__, 'work_pool_name'),
        work_queue_name=pulumi.get(__response__, 'work_queue_name'),
        workspace_id=pulumi.get(__response__, 'workspace_id')))
