# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ServiceAccountArgs', 'ServiceAccount']

@pulumi.input_type
class ServiceAccountArgs:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 account_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_expiration: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 old_key_expires_in_seconds: Optional[pulumi.Input[_builtins.float]] = None):
        """
        The set of arguments for constructing a ServiceAccount resource.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] account_role_name: Account Role name of the service account (one of: Admin, Member, Owner)
        :param pulumi.Input[_builtins.str] api_key_expiration: Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] api_key_keepers: A map of values that, if changed, will trigger a key rotation (but not a re-creation of the Service Account)
        :param pulumi.Input[_builtins.str] name: Name of the service account
        :param pulumi.Input[_builtins.float] old_key_expires_in_seconds: Provide this field to set an expiration for the currently active api key. If not provided or provided Null, the current key will be deleted. If provided, it cannot be more than 48 hours (172800 seconds) in the future.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if account_role_name is not None:
            pulumi.set(__self__, "account_role_name", account_role_name)
        if api_key_expiration is not None:
            pulumi.set(__self__, "api_key_expiration", api_key_expiration)
        if api_key_keepers is not None:
            pulumi.set(__self__, "api_key_keepers", api_key_keepers)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if old_key_expires_in_seconds is not None:
            pulumi.set(__self__, "old_key_expires_in_seconds", old_key_expires_in_seconds)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="accountRoleName")
    def account_role_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account Role name of the service account (one of: Admin, Member, Owner)
        """
        return pulumi.get(self, "account_role_name")

    @account_role_name.setter
    def account_role_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_role_name", value)

    @_builtins.property
    @pulumi.getter(name="apiKeyExpiration")
    def api_key_expiration(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
        """
        return pulumi.get(self, "api_key_expiration")

    @api_key_expiration.setter
    def api_key_expiration(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key_expiration", value)

    @_builtins.property
    @pulumi.getter(name="apiKeyKeepers")
    def api_key_keepers(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        A map of values that, if changed, will trigger a key rotation (but not a re-creation of the Service Account)
        """
        return pulumi.get(self, "api_key_keepers")

    @api_key_keepers.setter
    def api_key_keepers(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "api_key_keepers", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the service account
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="oldKeyExpiresInSeconds")
    def old_key_expires_in_seconds(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Provide this field to set an expiration for the currently active api key. If not provided or provided Null, the current key will be deleted. If provided, it cannot be more than 48 hours (172800 seconds) in the future.
        """
        return pulumi.get(self, "old_key_expires_in_seconds")

    @old_key_expires_in_seconds.setter
    def old_key_expires_in_seconds(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "old_key_expires_in_seconds", value)


@pulumi.input_type
class _ServiceAccountState:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 account_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 actor_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_created: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_expiration: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_id: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 api_key_name: Optional[pulumi.Input[_builtins.str]] = None,
                 created: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 old_key_expires_in_seconds: Optional[pulumi.Input[_builtins.float]] = None,
                 updated: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ServiceAccount resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] account_role_name: Account Role name of the service account (one of: Admin, Member, Owner)
        :param pulumi.Input[_builtins.str] actor_id: Actor ID (UUID), used for granting access to resources like Blocks and Deployments
        :param pulumi.Input[_builtins.str] api_key: API Key associated with the service account
        :param pulumi.Input[_builtins.str] api_key_created: Timestamp of the API Key creation (RFC3339)
        :param pulumi.Input[_builtins.str] api_key_expiration: Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
        :param pulumi.Input[_builtins.str] api_key_id: API Key ID associated with the service account
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] api_key_keepers: A map of values that, if changed, will trigger a key rotation (but not a re-creation of the Service Account)
        :param pulumi.Input[_builtins.str] api_key_name: API Key Name associated with the service account
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] name: Name of the service account
        :param pulumi.Input[_builtins.float] old_key_expires_in_seconds: Provide this field to set an expiration for the currently active api key. If not provided or provided Null, the current key will be deleted. If provided, it cannot be more than 48 hours (172800 seconds) in the future.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if account_role_name is not None:
            pulumi.set(__self__, "account_role_name", account_role_name)
        if actor_id is not None:
            pulumi.set(__self__, "actor_id", actor_id)
        if api_key is not None:
            pulumi.set(__self__, "api_key", api_key)
        if api_key_created is not None:
            pulumi.set(__self__, "api_key_created", api_key_created)
        if api_key_expiration is not None:
            pulumi.set(__self__, "api_key_expiration", api_key_expiration)
        if api_key_id is not None:
            pulumi.set(__self__, "api_key_id", api_key_id)
        if api_key_keepers is not None:
            pulumi.set(__self__, "api_key_keepers", api_key_keepers)
        if api_key_name is not None:
            pulumi.set(__self__, "api_key_name", api_key_name)
        if created is not None:
            pulumi.set(__self__, "created", created)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if old_key_expires_in_seconds is not None:
            pulumi.set(__self__, "old_key_expires_in_seconds", old_key_expires_in_seconds)
        if updated is not None:
            pulumi.set(__self__, "updated", updated)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="accountRoleName")
    def account_role_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account Role name of the service account (one of: Admin, Member, Owner)
        """
        return pulumi.get(self, "account_role_name")

    @account_role_name.setter
    def account_role_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_role_name", value)

    @_builtins.property
    @pulumi.getter(name="actorId")
    def actor_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Actor ID (UUID), used for granting access to resources like Blocks and Deployments
        """
        return pulumi.get(self, "actor_id")

    @actor_id.setter
    def actor_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "actor_id", value)

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API Key associated with the service account
        """
        return pulumi.get(self, "api_key")

    @api_key.setter
    def api_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key", value)

    @_builtins.property
    @pulumi.getter(name="apiKeyCreated")
    def api_key_created(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of the API Key creation (RFC3339)
        """
        return pulumi.get(self, "api_key_created")

    @api_key_created.setter
    def api_key_created(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key_created", value)

    @_builtins.property
    @pulumi.getter(name="apiKeyExpiration")
    def api_key_expiration(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
        """
        return pulumi.get(self, "api_key_expiration")

    @api_key_expiration.setter
    def api_key_expiration(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key_expiration", value)

    @_builtins.property
    @pulumi.getter(name="apiKeyId")
    def api_key_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API Key ID associated with the service account
        """
        return pulumi.get(self, "api_key_id")

    @api_key_id.setter
    def api_key_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key_id", value)

    @_builtins.property
    @pulumi.getter(name="apiKeyKeepers")
    def api_key_keepers(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        A map of values that, if changed, will trigger a key rotation (but not a re-creation of the Service Account)
        """
        return pulumi.get(self, "api_key_keepers")

    @api_key_keepers.setter
    def api_key_keepers(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "api_key_keepers", value)

    @_builtins.property
    @pulumi.getter(name="apiKeyName")
    def api_key_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        API Key Name associated with the service account
        """
        return pulumi.get(self, "api_key_name")

    @api_key_name.setter
    def api_key_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_key_name", value)

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the service account
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="oldKeyExpiresInSeconds")
    def old_key_expires_in_seconds(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Provide this field to set an expiration for the currently active api key. If not provided or provided Null, the current key will be deleted. If provided, it cannot be more than 48 hours (172800 seconds) in the future.
        """
        return pulumi.get(self, "old_key_expires_in_seconds")

    @old_key_expires_in_seconds.setter
    def old_key_expires_in_seconds(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "old_key_expires_in_seconds", value)

    @_builtins.property
    @pulumi.getter
    def updated(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @updated.setter
    def updated(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated", value)


@pulumi.type_token("prefect:index/serviceAccount:ServiceAccount")
class ServiceAccount(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 account_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_expiration: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 old_key_expires_in_seconds: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        """
        Create a ServiceAccount resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] account_role_name: Account Role name of the service account (one of: Admin, Member, Owner)
        :param pulumi.Input[_builtins.str] api_key_expiration: Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] api_key_keepers: A map of values that, if changed, will trigger a key rotation (but not a re-creation of the Service Account)
        :param pulumi.Input[_builtins.str] name: Name of the service account
        :param pulumi.Input[_builtins.float] old_key_expires_in_seconds: Provide this field to set an expiration for the currently active api key. If not provided or provided Null, the current key will be deleted. If provided, it cannot be more than 48 hours (172800 seconds) in the future.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ServiceAccountArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ServiceAccount resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ServiceAccountArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceAccountArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 account_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_expiration: Optional[pulumi.Input[_builtins.str]] = None,
                 api_key_keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 old_key_expires_in_seconds: Optional[pulumi.Input[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceAccountArgs.__new__(ServiceAccountArgs)

            __props__.__dict__["account_id"] = account_id
            __props__.__dict__["account_role_name"] = account_role_name
            __props__.__dict__["api_key_expiration"] = api_key_expiration
            __props__.__dict__["api_key_keepers"] = api_key_keepers
            __props__.__dict__["name"] = name
            __props__.__dict__["old_key_expires_in_seconds"] = old_key_expires_in_seconds
            __props__.__dict__["actor_id"] = None
            __props__.__dict__["api_key"] = None
            __props__.__dict__["api_key_created"] = None
            __props__.__dict__["api_key_id"] = None
            __props__.__dict__["api_key_name"] = None
            __props__.__dict__["created"] = None
            __props__.__dict__["updated"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ServiceAccount, __self__).__init__(
            'prefect:index/serviceAccount:ServiceAccount',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: Optional[pulumi.Input[_builtins.str]] = None,
            account_role_name: Optional[pulumi.Input[_builtins.str]] = None,
            actor_id: Optional[pulumi.Input[_builtins.str]] = None,
            api_key: Optional[pulumi.Input[_builtins.str]] = None,
            api_key_created: Optional[pulumi.Input[_builtins.str]] = None,
            api_key_expiration: Optional[pulumi.Input[_builtins.str]] = None,
            api_key_id: Optional[pulumi.Input[_builtins.str]] = None,
            api_key_keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            api_key_name: Optional[pulumi.Input[_builtins.str]] = None,
            created: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            old_key_expires_in_seconds: Optional[pulumi.Input[_builtins.float]] = None,
            updated: Optional[pulumi.Input[_builtins.str]] = None) -> 'ServiceAccount':
        """
        Get an existing ServiceAccount resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] account_role_name: Account Role name of the service account (one of: Admin, Member, Owner)
        :param pulumi.Input[_builtins.str] actor_id: Actor ID (UUID), used for granting access to resources like Blocks and Deployments
        :param pulumi.Input[_builtins.str] api_key: API Key associated with the service account
        :param pulumi.Input[_builtins.str] api_key_created: Timestamp of the API Key creation (RFC3339)
        :param pulumi.Input[_builtins.str] api_key_expiration: Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
        :param pulumi.Input[_builtins.str] api_key_id: API Key ID associated with the service account
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] api_key_keepers: A map of values that, if changed, will trigger a key rotation (but not a re-creation of the Service Account)
        :param pulumi.Input[_builtins.str] api_key_name: API Key Name associated with the service account
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] name: Name of the service account
        :param pulumi.Input[_builtins.float] old_key_expires_in_seconds: Provide this field to set an expiration for the currently active api key. If not provided or provided Null, the current key will be deleted. If provided, it cannot be more than 48 hours (172800 seconds) in the future.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServiceAccountState.__new__(_ServiceAccountState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["account_role_name"] = account_role_name
        __props__.__dict__["actor_id"] = actor_id
        __props__.__dict__["api_key"] = api_key
        __props__.__dict__["api_key_created"] = api_key_created
        __props__.__dict__["api_key_expiration"] = api_key_expiration
        __props__.__dict__["api_key_id"] = api_key_id
        __props__.__dict__["api_key_keepers"] = api_key_keepers
        __props__.__dict__["api_key_name"] = api_key_name
        __props__.__dict__["created"] = created
        __props__.__dict__["name"] = name
        __props__.__dict__["old_key_expires_in_seconds"] = old_key_expires_in_seconds
        __props__.__dict__["updated"] = updated
        return ServiceAccount(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[_builtins.str]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="accountRoleName")
    def account_role_name(self) -> pulumi.Output[_builtins.str]:
        """
        Account Role name of the service account (one of: Admin, Member, Owner)
        """
        return pulumi.get(self, "account_role_name")

    @_builtins.property
    @pulumi.getter(name="actorId")
    def actor_id(self) -> pulumi.Output[_builtins.str]:
        """
        Actor ID (UUID), used for granting access to resources like Blocks and Deployments
        """
        return pulumi.get(self, "actor_id")

    @_builtins.property
    @pulumi.getter(name="apiKey")
    def api_key(self) -> pulumi.Output[_builtins.str]:
        """
        API Key associated with the service account
        """
        return pulumi.get(self, "api_key")

    @_builtins.property
    @pulumi.getter(name="apiKeyCreated")
    def api_key_created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of the API Key creation (RFC3339)
        """
        return pulumi.get(self, "api_key_created")

    @_builtins.property
    @pulumi.getter(name="apiKeyExpiration")
    def api_key_expiration(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
        """
        return pulumi.get(self, "api_key_expiration")

    @_builtins.property
    @pulumi.getter(name="apiKeyId")
    def api_key_id(self) -> pulumi.Output[_builtins.str]:
        """
        API Key ID associated with the service account
        """
        return pulumi.get(self, "api_key_id")

    @_builtins.property
    @pulumi.getter(name="apiKeyKeepers")
    def api_key_keepers(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        A map of values that, if changed, will trigger a key rotation (but not a re-creation of the Service Account)
        """
        return pulumi.get(self, "api_key_keepers")

    @_builtins.property
    @pulumi.getter(name="apiKeyName")
    def api_key_name(self) -> pulumi.Output[_builtins.str]:
        """
        API Key Name associated with the service account
        """
        return pulumi.get(self, "api_key_name")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the service account
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="oldKeyExpiresInSeconds")
    def old_key_expires_in_seconds(self) -> pulumi.Output[_builtins.float]:
        """
        Provide this field to set an expiration for the currently active api key. If not provided or provided Null, the current key will be deleted. If provided, it cannot be more than 48 hours (172800 seconds) in the future.
        """
        return pulumi.get(self, "old_key_expires_in_seconds")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

