# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['TeamAccessArgs', 'TeamAccess']

@pulumi.input_type
class TeamAccessArgs:
    def __init__(__self__, *,
                 member_actor_id: pulumi.Input[_builtins.str],
                 member_id: pulumi.Input[_builtins.str],
                 member_type: pulumi.Input[_builtins.str],
                 team_id: pulumi.Input[_builtins.str],
                 account_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a TeamAccess resource.

        :param pulumi.Input[_builtins.str] member_actor_id: Member Actor ID (UUID)
        :param pulumi.Input[_builtins.str] member_id: Member ID (UUID)
        :param pulumi.Input[_builtins.str] member_type: Member Type (user | service_account)
        :param pulumi.Input[_builtins.str] team_id: Team ID (UUID)
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID)
        """
        pulumi.set(__self__, "member_actor_id", member_actor_id)
        pulumi.set(__self__, "member_id", member_id)
        pulumi.set(__self__, "member_type", member_type)
        pulumi.set(__self__, "team_id", team_id)
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)

    @_builtins.property
    @pulumi.getter(name="memberActorId")
    def member_actor_id(self) -> pulumi.Input[_builtins.str]:
        """
        Member Actor ID (UUID)
        """
        return pulumi.get(self, "member_actor_id")

    @member_actor_id.setter
    def member_actor_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "member_actor_id", value)

    @_builtins.property
    @pulumi.getter(name="memberId")
    def member_id(self) -> pulumi.Input[_builtins.str]:
        """
        Member ID (UUID)
        """
        return pulumi.get(self, "member_id")

    @member_id.setter
    def member_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "member_id", value)

    @_builtins.property
    @pulumi.getter(name="memberType")
    def member_type(self) -> pulumi.Input[_builtins.str]:
        """
        Member Type (user | service_account)
        """
        return pulumi.get(self, "member_type")

    @member_type.setter
    def member_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "member_type", value)

    @_builtins.property
    @pulumi.getter(name="teamId")
    def team_id(self) -> pulumi.Input[_builtins.str]:
        """
        Team ID (UUID)
        """
        return pulumi.get(self, "team_id")

    @team_id.setter
    def team_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "team_id", value)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID)
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)


@pulumi.input_type
class _TeamAccessState:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_actor_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_type: Optional[pulumi.Input[_builtins.str]] = None,
                 team_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering TeamAccess resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID)
        :param pulumi.Input[_builtins.str] member_actor_id: Member Actor ID (UUID)
        :param pulumi.Input[_builtins.str] member_id: Member ID (UUID)
        :param pulumi.Input[_builtins.str] member_type: Member Type (user | service_account)
        :param pulumi.Input[_builtins.str] team_id: Team ID (UUID)
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if member_actor_id is not None:
            pulumi.set(__self__, "member_actor_id", member_actor_id)
        if member_id is not None:
            pulumi.set(__self__, "member_id", member_id)
        if member_type is not None:
            pulumi.set(__self__, "member_type", member_type)
        if team_id is not None:
            pulumi.set(__self__, "team_id", team_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID)
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="memberActorId")
    def member_actor_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Member Actor ID (UUID)
        """
        return pulumi.get(self, "member_actor_id")

    @member_actor_id.setter
    def member_actor_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "member_actor_id", value)

    @_builtins.property
    @pulumi.getter(name="memberId")
    def member_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Member ID (UUID)
        """
        return pulumi.get(self, "member_id")

    @member_id.setter
    def member_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "member_id", value)

    @_builtins.property
    @pulumi.getter(name="memberType")
    def member_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Member Type (user | service_account)
        """
        return pulumi.get(self, "member_type")

    @member_type.setter
    def member_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "member_type", value)

    @_builtins.property
    @pulumi.getter(name="teamId")
    def team_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Team ID (UUID)
        """
        return pulumi.get(self, "team_id")

    @team_id.setter
    def team_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "team_id", value)


@pulumi.type_token("prefect:index/teamAccess:TeamAccess")
class TeamAccess(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_actor_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_type: Optional[pulumi.Input[_builtins.str]] = None,
                 team_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a TeamAccess resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID)
        :param pulumi.Input[_builtins.str] member_actor_id: Member Actor ID (UUID)
        :param pulumi.Input[_builtins.str] member_id: Member ID (UUID)
        :param pulumi.Input[_builtins.str] member_type: Member Type (user | service_account)
        :param pulumi.Input[_builtins.str] team_id: Team ID (UUID)
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TeamAccessArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a TeamAccess resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param TeamAccessArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TeamAccessArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_actor_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_id: Optional[pulumi.Input[_builtins.str]] = None,
                 member_type: Optional[pulumi.Input[_builtins.str]] = None,
                 team_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TeamAccessArgs.__new__(TeamAccessArgs)

            __props__.__dict__["account_id"] = account_id
            if member_actor_id is None and not opts.urn:
                raise TypeError("Missing required property 'member_actor_id'")
            __props__.__dict__["member_actor_id"] = member_actor_id
            if member_id is None and not opts.urn:
                raise TypeError("Missing required property 'member_id'")
            __props__.__dict__["member_id"] = member_id
            if member_type is None and not opts.urn:
                raise TypeError("Missing required property 'member_type'")
            __props__.__dict__["member_type"] = member_type
            if team_id is None and not opts.urn:
                raise TypeError("Missing required property 'team_id'")
            __props__.__dict__["team_id"] = team_id
        super(TeamAccess, __self__).__init__(
            'prefect:index/teamAccess:TeamAccess',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: Optional[pulumi.Input[_builtins.str]] = None,
            member_actor_id: Optional[pulumi.Input[_builtins.str]] = None,
            member_id: Optional[pulumi.Input[_builtins.str]] = None,
            member_type: Optional[pulumi.Input[_builtins.str]] = None,
            team_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'TeamAccess':
        """
        Get an existing TeamAccess resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID)
        :param pulumi.Input[_builtins.str] member_actor_id: Member Actor ID (UUID)
        :param pulumi.Input[_builtins.str] member_id: Member ID (UUID)
        :param pulumi.Input[_builtins.str] member_type: Member Type (user | service_account)
        :param pulumi.Input[_builtins.str] team_id: Team ID (UUID)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TeamAccessState.__new__(_TeamAccessState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["member_actor_id"] = member_actor_id
        __props__.__dict__["member_id"] = member_id
        __props__.__dict__["member_type"] = member_type
        __props__.__dict__["team_id"] = team_id
        return TeamAccess(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Account ID (UUID)
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="memberActorId")
    def member_actor_id(self) -> pulumi.Output[_builtins.str]:
        """
        Member Actor ID (UUID)
        """
        return pulumi.get(self, "member_actor_id")

    @_builtins.property
    @pulumi.getter(name="memberId")
    def member_id(self) -> pulumi.Output[_builtins.str]:
        """
        Member ID (UUID)
        """
        return pulumi.get(self, "member_id")

    @_builtins.property
    @pulumi.getter(name="memberType")
    def member_type(self) -> pulumi.Output[_builtins.str]:
        """
        Member Type (user | service_account)
        """
        return pulumi.get(self, "member_type")

    @_builtins.property
    @pulumi.getter(name="teamId")
    def team_id(self) -> pulumi.Output[_builtins.str]:
        """
        Team ID (UUID)
        """
        return pulumi.get(self, "team_id")

