# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WorkspaceAccessArgs', 'WorkspaceAccess']

@pulumi.input_type
class WorkspaceAccessArgs:
    def __init__(__self__, *,
                 accessor_id: pulumi.Input[_builtins.str],
                 accessor_type: pulumi.Input[_builtins.str],
                 workspace_role_id: pulumi.Input[_builtins.str],
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a WorkspaceAccess resource.

        :param pulumi.Input[_builtins.str] accessor_id: ID (UUID) of accessor to the workspace. This can be an `account_member.user_id` or `service_account.id`
        :param pulumi.Input[_builtins.str] accessor_type: USER | SERVICE_ACCOUNT | TEAM
        :param pulumi.Input[_builtins.str] workspace_role_id: Workspace Role ID (UUID) to grant to accessor
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the workspace is located
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) to grant access to
        """
        pulumi.set(__self__, "accessor_id", accessor_id)
        pulumi.set(__self__, "accessor_type", accessor_type)
        pulumi.set(__self__, "workspace_role_id", workspace_role_id)
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accessorId")
    def accessor_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID (UUID) of accessor to the workspace. This can be an `account_member.user_id` or `service_account.id`
        """
        return pulumi.get(self, "accessor_id")

    @accessor_id.setter
    def accessor_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "accessor_id", value)

    @_builtins.property
    @pulumi.getter(name="accessorType")
    def accessor_type(self) -> pulumi.Input[_builtins.str]:
        """
        USER | SERVICE_ACCOUNT | TEAM
        """
        return pulumi.get(self, "accessor_type")

    @accessor_type.setter
    def accessor_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "accessor_type", value)

    @_builtins.property
    @pulumi.getter(name="workspaceRoleId")
    def workspace_role_id(self) -> pulumi.Input[_builtins.str]:
        """
        Workspace Role ID (UUID) to grant to accessor
        """
        return pulumi.get(self, "workspace_role_id")

    @workspace_role_id.setter
    def workspace_role_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "workspace_role_id", value)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID) where the workspace is located
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID) to grant access to
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.input_type
class _WorkspaceAccessState:
    def __init__(__self__, *,
                 accessor_id: Optional[pulumi.Input[_builtins.str]] = None,
                 accessor_type: Optional[pulumi.Input[_builtins.str]] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_role_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering WorkspaceAccess resources.

        :param pulumi.Input[_builtins.str] accessor_id: ID (UUID) of accessor to the workspace. This can be an `account_member.user_id` or `service_account.id`
        :param pulumi.Input[_builtins.str] accessor_type: USER | SERVICE_ACCOUNT | TEAM
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the workspace is located
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) to grant access to
        :param pulumi.Input[_builtins.str] workspace_role_id: Workspace Role ID (UUID) to grant to accessor
        """
        if accessor_id is not None:
            pulumi.set(__self__, "accessor_id", accessor_id)
        if accessor_type is not None:
            pulumi.set(__self__, "accessor_type", accessor_type)
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)
        if workspace_role_id is not None:
            pulumi.set(__self__, "workspace_role_id", workspace_role_id)

    @_builtins.property
    @pulumi.getter(name="accessorId")
    def accessor_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID (UUID) of accessor to the workspace. This can be an `account_member.user_id` or `service_account.id`
        """
        return pulumi.get(self, "accessor_id")

    @accessor_id.setter
    def accessor_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "accessor_id", value)

    @_builtins.property
    @pulumi.getter(name="accessorType")
    def accessor_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        USER | SERVICE_ACCOUNT | TEAM
        """
        return pulumi.get(self, "accessor_type")

    @accessor_type.setter
    def accessor_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "accessor_type", value)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID) where the workspace is located
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID) to grant access to
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)

    @_builtins.property
    @pulumi.getter(name="workspaceRoleId")
    def workspace_role_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace Role ID (UUID) to grant to accessor
        """
        return pulumi.get(self, "workspace_role_id")

    @workspace_role_id.setter
    def workspace_role_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_role_id", value)


@pulumi.type_token("prefect:index/workspaceAccess:WorkspaceAccess")
class WorkspaceAccess(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accessor_id: Optional[pulumi.Input[_builtins.str]] = None,
                 accessor_type: Optional[pulumi.Input[_builtins.str]] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_role_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a WorkspaceAccess resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] accessor_id: ID (UUID) of accessor to the workspace. This can be an `account_member.user_id` or `service_account.id`
        :param pulumi.Input[_builtins.str] accessor_type: USER | SERVICE_ACCOUNT | TEAM
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the workspace is located
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) to grant access to
        :param pulumi.Input[_builtins.str] workspace_role_id: Workspace Role ID (UUID) to grant to accessor
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WorkspaceAccessArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WorkspaceAccess resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param WorkspaceAccessArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkspaceAccessArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accessor_id: Optional[pulumi.Input[_builtins.str]] = None,
                 accessor_type: Optional[pulumi.Input[_builtins.str]] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_role_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkspaceAccessArgs.__new__(WorkspaceAccessArgs)

            if accessor_id is None and not opts.urn:
                raise TypeError("Missing required property 'accessor_id'")
            __props__.__dict__["accessor_id"] = accessor_id
            if accessor_type is None and not opts.urn:
                raise TypeError("Missing required property 'accessor_type'")
            __props__.__dict__["accessor_type"] = accessor_type
            __props__.__dict__["account_id"] = account_id
            __props__.__dict__["workspace_id"] = workspace_id
            if workspace_role_id is None and not opts.urn:
                raise TypeError("Missing required property 'workspace_role_id'")
            __props__.__dict__["workspace_role_id"] = workspace_role_id
        super(WorkspaceAccess, __self__).__init__(
            'prefect:index/workspaceAccess:WorkspaceAccess',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            accessor_id: Optional[pulumi.Input[_builtins.str]] = None,
            accessor_type: Optional[pulumi.Input[_builtins.str]] = None,
            account_id: Optional[pulumi.Input[_builtins.str]] = None,
            workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
            workspace_role_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'WorkspaceAccess':
        """
        Get an existing WorkspaceAccess resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] accessor_id: ID (UUID) of accessor to the workspace. This can be an `account_member.user_id` or `service_account.id`
        :param pulumi.Input[_builtins.str] accessor_type: USER | SERVICE_ACCOUNT | TEAM
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID) where the workspace is located
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID) to grant access to
        :param pulumi.Input[_builtins.str] workspace_role_id: Workspace Role ID (UUID) to grant to accessor
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkspaceAccessState.__new__(_WorkspaceAccessState)

        __props__.__dict__["accessor_id"] = accessor_id
        __props__.__dict__["accessor_type"] = accessor_type
        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["workspace_id"] = workspace_id
        __props__.__dict__["workspace_role_id"] = workspace_role_id
        return WorkspaceAccess(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessorId")
    def accessor_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID (UUID) of accessor to the workspace. This can be an `account_member.user_id` or `service_account.id`
        """
        return pulumi.get(self, "accessor_id")

    @_builtins.property
    @pulumi.getter(name="accessorType")
    def accessor_type(self) -> pulumi.Output[_builtins.str]:
        """
        USER | SERVICE_ACCOUNT | TEAM
        """
        return pulumi.get(self, "accessor_type")

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Account ID (UUID) where the workspace is located
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Workspace ID (UUID) to grant access to
        """
        return pulumi.get(self, "workspace_id")

    @_builtins.property
    @pulumi.getter(name="workspaceRoleId")
    def workspace_role_id(self) -> pulumi.Output[_builtins.str]:
        """
        Workspace Role ID (UUID) to grant to accessor
        """
        return pulumi.get(self, "workspace_role_id")

