# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WorkPoolArgs', 'WorkPool']

@pulumi.input_type
class WorkPoolArgs:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 base_job_template: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a WorkPool resource.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] base_job_template: The base job template for the work pool, as a JSON string
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work pool
        :param pulumi.Input[_builtins.str] description: Description of the work pool
        :param pulumi.Input[_builtins.str] name: Name of the work pool
        :param pulumi.Input[_builtins.bool] paused: Whether this work pool is paused
        :param pulumi.Input[_builtins.str] type: Type of the work pool, eg. kubernetes, ecs, process, etc.
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if base_job_template is not None:
            pulumi.set(__self__, "base_job_template", base_job_template)
        if concurrency_limit is not None:
            pulumi.set(__self__, "concurrency_limit", concurrency_limit)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if paused is not None:
            pulumi.set(__self__, "paused", paused)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="baseJobTemplate")
    def base_job_template(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The base job template for the work pool, as a JSON string
        """
        return pulumi.get(self, "base_job_template")

    @base_job_template.setter
    def base_job_template(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "base_job_template", value)

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The concurrency limit applied to this work pool
        """
        return pulumi.get(self, "concurrency_limit")

    @concurrency_limit.setter
    def concurrency_limit(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "concurrency_limit", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the work pool
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the work pool
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def paused(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether this work pool is paused
        """
        return pulumi.get(self, "paused")

    @paused.setter
    def paused(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "paused", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Type of the work pool, eg. kubernetes, ecs, process, etc.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.input_type
class _WorkPoolState:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 base_job_template: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 created: Optional[pulumi.Input[_builtins.str]] = None,
                 default_queue_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 updated: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering WorkPool resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] base_job_template: The base job template for the work pool, as a JSON string
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work pool
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] default_queue_id: The ID (UUID) of the default queue associated with this work pool
        :param pulumi.Input[_builtins.str] description: Description of the work pool
        :param pulumi.Input[_builtins.str] name: Name of the work pool
        :param pulumi.Input[_builtins.bool] paused: Whether this work pool is paused
        :param pulumi.Input[_builtins.str] type: Type of the work pool, eg. kubernetes, ecs, process, etc.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if base_job_template is not None:
            pulumi.set(__self__, "base_job_template", base_job_template)
        if concurrency_limit is not None:
            pulumi.set(__self__, "concurrency_limit", concurrency_limit)
        if created is not None:
            pulumi.set(__self__, "created", created)
        if default_queue_id is not None:
            pulumi.set(__self__, "default_queue_id", default_queue_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if paused is not None:
            pulumi.set(__self__, "paused", paused)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if updated is not None:
            pulumi.set(__self__, "updated", updated)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="baseJobTemplate")
    def base_job_template(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The base job template for the work pool, as a JSON string
        """
        return pulumi.get(self, "base_job_template")

    @base_job_template.setter
    def base_job_template(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "base_job_template", value)

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The concurrency limit applied to this work pool
        """
        return pulumi.get(self, "concurrency_limit")

    @concurrency_limit.setter
    def concurrency_limit(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "concurrency_limit", value)

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter(name="defaultQueueId")
    def default_queue_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID (UUID) of the default queue associated with this work pool
        """
        return pulumi.get(self, "default_queue_id")

    @default_queue_id.setter
    def default_queue_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "default_queue_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the work pool
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the work pool
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def paused(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether this work pool is paused
        """
        return pulumi.get(self, "paused")

    @paused.setter
    def paused(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "paused", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Type of the work pool, eg. kubernetes, ecs, process, etc.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def updated(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @updated.setter
    def updated(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.type_token("prefect:index/workPool:WorkPool")
class WorkPool(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 base_job_template: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a WorkPool resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] base_job_template: The base job template for the work pool, as a JSON string
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work pool
        :param pulumi.Input[_builtins.str] description: Description of the work pool
        :param pulumi.Input[_builtins.str] name: Name of the work pool
        :param pulumi.Input[_builtins.bool] paused: Whether this work pool is paused
        :param pulumi.Input[_builtins.str] type: Type of the work pool, eg. kubernetes, ecs, process, etc.
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[WorkPoolArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WorkPool resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param WorkPoolArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkPoolArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 base_job_template: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkPoolArgs.__new__(WorkPoolArgs)

            __props__.__dict__["account_id"] = account_id
            __props__.__dict__["base_job_template"] = base_job_template
            __props__.__dict__["concurrency_limit"] = concurrency_limit
            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            __props__.__dict__["paused"] = paused
            __props__.__dict__["type"] = type
            __props__.__dict__["workspace_id"] = workspace_id
            __props__.__dict__["created"] = None
            __props__.__dict__["default_queue_id"] = None
            __props__.__dict__["updated"] = None
        super(WorkPool, __self__).__init__(
            'prefect:index/workPool:WorkPool',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: Optional[pulumi.Input[_builtins.str]] = None,
            base_job_template: Optional[pulumi.Input[_builtins.str]] = None,
            concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
            created: Optional[pulumi.Input[_builtins.str]] = None,
            default_queue_id: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            paused: Optional[pulumi.Input[_builtins.bool]] = None,
            type: Optional[pulumi.Input[_builtins.str]] = None,
            updated: Optional[pulumi.Input[_builtins.str]] = None,
            workspace_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'WorkPool':
        """
        Get an existing WorkPool resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.str] base_job_template: The base job template for the work pool, as a JSON string
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work pool
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] default_queue_id: The ID (UUID) of the default queue associated with this work pool
        :param pulumi.Input[_builtins.str] description: Description of the work pool
        :param pulumi.Input[_builtins.str] name: Name of the work pool
        :param pulumi.Input[_builtins.bool] paused: Whether this work pool is paused
        :param pulumi.Input[_builtins.str] type: Type of the work pool, eg. kubernetes, ecs, process, etc.
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkPoolState.__new__(_WorkPoolState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["base_job_template"] = base_job_template
        __props__.__dict__["concurrency_limit"] = concurrency_limit
        __props__.__dict__["created"] = created
        __props__.__dict__["default_queue_id"] = default_queue_id
        __props__.__dict__["description"] = description
        __props__.__dict__["name"] = name
        __props__.__dict__["paused"] = paused
        __props__.__dict__["type"] = type
        __props__.__dict__["updated"] = updated
        __props__.__dict__["workspace_id"] = workspace_id
        return WorkPool(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="baseJobTemplate")
    def base_job_template(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The base job template for the work pool, as a JSON string
        """
        return pulumi.get(self, "base_job_template")

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The concurrency limit applied to this work pool
        """
        return pulumi.get(self, "concurrency_limit")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter(name="defaultQueueId")
    def default_queue_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID (UUID) of the default queue associated with this work pool
        """
        return pulumi.get(self, "default_queue_id")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the work pool
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the work pool
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def paused(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether this work pool is paused
        """
        return pulumi.get(self, "paused")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        Type of the work pool, eg. kubernetes, ecs, process, etc.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

