# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['WorkQueueArgs', 'WorkQueue']

@pulumi.input_type
class WorkQueueArgs:
    def __init__(__self__, *,
                 work_pool_name: pulumi.Input[_builtins.str],
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 priority: Optional[pulumi.Input[_builtins.float]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a WorkQueue resource.

        :param pulumi.Input[_builtins.str] work_pool_name: The name of the work pool associated with this work queue
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work queue
        :param pulumi.Input[_builtins.str] description: Description of the work queue
        :param pulumi.Input[_builtins.bool] is_paused: Whether this work queue is paused
        :param pulumi.Input[_builtins.str] name: Name of the work queue
        :param pulumi.Input[_builtins.float] priority: The priority of this work queue
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        pulumi.set(__self__, "work_pool_name", work_pool_name)
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if concurrency_limit is not None:
            pulumi.set(__self__, "concurrency_limit", concurrency_limit)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_paused is not None:
            pulumi.set(__self__, "is_paused", is_paused)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="workPoolName")
    def work_pool_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the work pool associated with this work queue
        """
        return pulumi.get(self, "work_pool_name")

    @work_pool_name.setter
    def work_pool_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "work_pool_name", value)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The concurrency limit applied to this work queue
        """
        return pulumi.get(self, "concurrency_limit")

    @concurrency_limit.setter
    def concurrency_limit(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "concurrency_limit", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the work queue
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="isPaused")
    def is_paused(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether this work queue is paused
        """
        return pulumi.get(self, "is_paused")

    @is_paused.setter
    def is_paused(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_paused", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the work queue
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def priority(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The priority of this work queue
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "priority", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.input_type
class _WorkQueueState:
    def __init__(__self__, *,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 created: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 priority: Optional[pulumi.Input[_builtins.float]] = None,
                 updated: Optional[pulumi.Input[_builtins.str]] = None,
                 work_pool_name: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering WorkQueue resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work queue
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] description: Description of the work queue
        :param pulumi.Input[_builtins.bool] is_paused: Whether this work queue is paused
        :param pulumi.Input[_builtins.str] name: Name of the work queue
        :param pulumi.Input[_builtins.float] priority: The priority of this work queue
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] work_pool_name: The name of the work pool associated with this work queue
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if concurrency_limit is not None:
            pulumi.set(__self__, "concurrency_limit", concurrency_limit)
        if created is not None:
            pulumi.set(__self__, "created", created)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_paused is not None:
            pulumi.set(__self__, "is_paused", is_paused)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)
        if updated is not None:
            pulumi.set(__self__, "updated", updated)
        if work_pool_name is not None:
            pulumi.set(__self__, "work_pool_name", work_pool_name)
        if workspace_id is not None:
            pulumi.set(__self__, "workspace_id", workspace_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The concurrency limit applied to this work queue
        """
        return pulumi.get(self, "concurrency_limit")

    @concurrency_limit.setter
    def concurrency_limit(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "concurrency_limit", value)

    @_builtins.property
    @pulumi.getter
    def created(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @created.setter
    def created(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the work queue
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="isPaused")
    def is_paused(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether this work queue is paused
        """
        return pulumi.get(self, "is_paused")

    @is_paused.setter
    def is_paused(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_paused", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the work queue
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def priority(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The priority of this work queue
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "priority", value)

    @_builtins.property
    @pulumi.getter
    def updated(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @updated.setter
    def updated(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated", value)

    @_builtins.property
    @pulumi.getter(name="workPoolName")
    def work_pool_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the work pool associated with this work queue
        """
        return pulumi.get(self, "work_pool_name")

    @work_pool_name.setter
    def work_pool_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "work_pool_name", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "workspace_id", value)


@pulumi.type_token("prefect:index/workQueue:WorkQueue")
class WorkQueue(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 priority: Optional[pulumi.Input[_builtins.float]] = None,
                 work_pool_name: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a WorkQueue resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work queue
        :param pulumi.Input[_builtins.str] description: Description of the work queue
        :param pulumi.Input[_builtins.bool] is_paused: Whether this work queue is paused
        :param pulumi.Input[_builtins.str] name: Name of the work queue
        :param pulumi.Input[_builtins.float] priority: The priority of this work queue
        :param pulumi.Input[_builtins.str] work_pool_name: The name of the work pool associated with this work queue
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: WorkQueueArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a WorkQueue resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param WorkQueueArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(WorkQueueArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_id: Optional[pulumi.Input[_builtins.str]] = None,
                 concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 priority: Optional[pulumi.Input[_builtins.float]] = None,
                 work_pool_name: Optional[pulumi.Input[_builtins.str]] = None,
                 workspace_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = WorkQueueArgs.__new__(WorkQueueArgs)

            __props__.__dict__["account_id"] = account_id
            __props__.__dict__["concurrency_limit"] = concurrency_limit
            __props__.__dict__["description"] = description
            __props__.__dict__["is_paused"] = is_paused
            __props__.__dict__["name"] = name
            __props__.__dict__["priority"] = priority
            if work_pool_name is None and not opts.urn:
                raise TypeError("Missing required property 'work_pool_name'")
            __props__.__dict__["work_pool_name"] = work_pool_name
            __props__.__dict__["workspace_id"] = workspace_id
            __props__.__dict__["created"] = None
            __props__.__dict__["updated"] = None
        super(WorkQueue, __self__).__init__(
            'prefect:index/workQueue:WorkQueue',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            account_id: Optional[pulumi.Input[_builtins.str]] = None,
            concurrency_limit: Optional[pulumi.Input[_builtins.float]] = None,
            created: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            is_paused: Optional[pulumi.Input[_builtins.bool]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            priority: Optional[pulumi.Input[_builtins.float]] = None,
            updated: Optional[pulumi.Input[_builtins.str]] = None,
            work_pool_name: Optional[pulumi.Input[_builtins.str]] = None,
            workspace_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'WorkQueue':
        """
        Get an existing WorkQueue resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID (UUID), defaults to the account set in the provider
        :param pulumi.Input[_builtins.float] concurrency_limit: The concurrency limit applied to this work queue
        :param pulumi.Input[_builtins.str] created: Timestamp of when the resource was created (RFC3339)
        :param pulumi.Input[_builtins.str] description: Description of the work queue
        :param pulumi.Input[_builtins.bool] is_paused: Whether this work queue is paused
        :param pulumi.Input[_builtins.str] name: Name of the work queue
        :param pulumi.Input[_builtins.float] priority: The priority of this work queue
        :param pulumi.Input[_builtins.str] updated: Timestamp of when the resource was updated (RFC3339)
        :param pulumi.Input[_builtins.str] work_pool_name: The name of the work pool associated with this work queue
        :param pulumi.Input[_builtins.str] workspace_id: Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _WorkQueueState.__new__(_WorkQueueState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["concurrency_limit"] = concurrency_limit
        __props__.__dict__["created"] = created
        __props__.__dict__["description"] = description
        __props__.__dict__["is_paused"] = is_paused
        __props__.__dict__["name"] = name
        __props__.__dict__["priority"] = priority
        __props__.__dict__["updated"] = updated
        __props__.__dict__["work_pool_name"] = work_pool_name
        __props__.__dict__["workspace_id"] = workspace_id
        return WorkQueue(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Account ID (UUID), defaults to the account set in the provider
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="concurrencyLimit")
    def concurrency_limit(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        The concurrency limit applied to this work queue
        """
        return pulumi.get(self, "concurrency_limit")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was created (RFC3339)
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        Description of the work queue
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="isPaused")
    def is_paused(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether this work queue is paused
        """
        return pulumi.get(self, "is_paused")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the work queue
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def priority(self) -> pulumi.Output[_builtins.float]:
        """
        The priority of this work queue
        """
        return pulumi.get(self, "priority")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp of when the resource was updated (RFC3339)
        """
        return pulumi.get(self, "updated")

    @_builtins.property
    @pulumi.getter(name="workPoolName")
    def work_pool_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the work pool associated with this work queue
        """
        return pulumi.get(self, "work_pool_name")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Workspace ID (UUID), defaults to the workspace set in the provider. In Prefect Cloud, either the <span pulumi-lang-nodejs="`workPool`" pulumi-lang-dotnet="`WorkPool`" pulumi-lang-go="`workPool`" pulumi-lang-python="`work_pool`" pulumi-lang-yaml="`workPool`" pulumi-lang-java="`workPool`">`work_pool`</span> resource or the provider's <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> must be set.
        """
        return pulumi.get(self, "workspace_id")

