version: 2

models:
  - name: dim_item
    description: >
      Core dimension table containing all static and slowly changing
      attributes  for CS2 market items. Denormalized for easier querying.
    columns:
      - name: item_name
        description: Name of the market item. Serves as the natural primary key.
        data_tests:
          - unique
          - not_null
      - name: class_id
        description: Identifier for the item class.
      - name: bucket_group_id
        description: String identifier for the market bucket group.
      - name: bucket_group_name
        description: Name of the market bucket group.
      - name: item_type
        description: Type of the item (e.g. 'Covert Rifle', 'Base Grade Container', etc.).
      - name: name_color
        description: Hex color code indicating rarity or special attributes.
      - name: is_tradable
        description: Boolean flag indicating if the item is tradable.
      - name: is_commodity
        description: Boolean indicating if the item is a distinct commodity without
          variations.
      - name: snapshot_date
        description: Date of the item snapshot
        data_tests:
          - not_null

  - name: fct_market_daily
    description: |
      Fact table containing daily market KPIs for each item, including prices, volumes, spreads, and calculated metrics. Incrementally loaded and partitioned by market_date for efficient querying.
    columns:
      - name: item_name
        description: Name of the market item.
        data_tests:
          - not_null
      - name: ask_count
        description: Number of active sell orders for the item on the market snapshot date.
        data_tests:
          - not_null
      - name: ask_price_usd
        description: Lowest listed price (USD) for the item on the market snapshot date.
        data_tests:
          - not_null
      - name: bid_price_usd
        description: Highest buy order price (USD) for the item on the market snapshot date.
        data_tests:
          - not_null
      - name: units_sold
        description: Number of units sold for the item on the given date.
        data_tests:
          - not_null
      - name: total_estimated_trade_volume_usd
        description: >
          Total estimated trade volume (USD) for the item on the given date.
          It's estimated because we are only have access to the median sale
          price, not the actual sale price for each unit sold.
        data_tests:
          - not_null
      - name: avg_median_sale_price_usd
        description: Median sale price (USD) for the item on the given date.
        data_tests:
          - not_null
      - name: bid_ask_spread_pct
        description: Percentage spread between ask and bid prices. Calculated as
          (ask_price_usd - bid_price_usd) / bid_price_usd.
        data_tests:
          - not_null
      - name: turnover_rate
        description: Ratio of units sold to ask count. Indicates market liquidity for
          the item.
        data_tests:
          - not_null
      - name: quick_sell_ratio
        description: Ratio of bid price to ask price. Indicates how quickly an item may
          sell at market prices.
        data_tests:
          - not_null
      - name: market_date
        description: Date of the market snapshot (partition key).
        data_tests:
          - not_null
