# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('prefect')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def account_id(self) -> Optional[str]:
        """
        Default Prefect Cloud Account ID. Can also be set via the `PREFECT_CLOUD_ACCOUNT_ID` environment variable.
        """
        return __config__.get('accountId')

    @_builtins.property
    def api_key(self) -> Optional[str]:
        """
        Prefect Cloud API key. Can also be set via the `PREFECT_API_KEY` environment variable.
        """
        return __config__.get('apiKey')

    @_builtins.property
    def basic_auth_key(self) -> Optional[str]:
        """
        Prefect basic auth key. Can also be set via the `PREFECT_BASIC_AUTH_KEY` environment variable.
        """
        return __config__.get('basicAuthKey')

    @_builtins.property
    def csrf_enabled(self) -> Optional[bool]:
        """
        Enable CSRF protection for API requests. Defaults to false. If enabled, the provider will fetch a CSRF token from the Prefect API and include it in all requests. This should be enabled if your Prefect server instance has CSRF protection active. Can also be set via the `PREFECT_CSRF_ENABLED` environment variable.
        """
        return __config__.get_bool('csrfEnabled')

    @_builtins.property
    def custom_headers(self) -> Optional[str]:
        """
        Custom HTTP headers to include in all Prefect API requests as a JSON string. Useful for adding authentication headers required by proxies, CDNs, or security systems like Cloudflare Access. Can also be set via the `PREFECT_CLIENT_CUSTOM_HEADERS` environment variable. Example: `{"CF-Access-Client-Id": "your-id", "CF-Access-Client-Secret": "your-secret"}`. Protected headers (User-Agent, Prefect-Csrf-Token, Prefect-Csrf-Client) cannot be overridden.
        """
        return __config__.get('customHeaders')

    @_builtins.property
    def endpoint(self) -> Optional[str]:
        """
        The Prefect API URL. Can also be set via the `PREFECT_API_URL` environment variable. Defaults to `https://api.prefect.cloud` if not configured. Can optionally include the default account ID and workspace ID in the following format: `https://api.prefect.cloud/api/accounts/<accountID>/workspaces/<workspaceID>`. This is the same format used for the `PREFECT_API_URL` value in the Prefect CLI configuration file. The <span pulumi-lang-nodejs="`accountId`" pulumi-lang-dotnet="`AccountId`" pulumi-lang-go="`accountId`" pulumi-lang-python="`account_id`" pulumi-lang-yaml="`accountId`" pulumi-lang-java="`accountId`">`account_id`</span> and <span pulumi-lang-nodejs="`workspaceId`" pulumi-lang-dotnet="`WorkspaceId`" pulumi-lang-go="`workspaceId`" pulumi-lang-python="`workspace_id`" pulumi-lang-yaml="`workspaceId`" pulumi-lang-java="`workspaceId`">`workspace_id`</span> attributes and their matching environment variables will take priority over any account and workspace ID values provided in the <span pulumi-lang-nodejs="`endpoint`" pulumi-lang-dotnet="`Endpoint`" pulumi-lang-go="`endpoint`" pulumi-lang-python="`endpoint`" pulumi-lang-yaml="`endpoint`" pulumi-lang-java="`endpoint`">`endpoint`</span> attribute.
        """
        return __config__.get('endpoint')

    @_builtins.property
    def profile(self) -> Optional[str]:
        """
        Prefect profile name to use for authentication. If not specified, uses the active profile from `~/.prefect/profiles.toml`. This allows you to use a specific profile instead of the active one.
        """
        return __config__.get('profile')

    @_builtins.property
    def profile_file(self) -> Optional[str]:
        """
        Path to the Prefect profiles file. If not specified, uses the default location `~/.prefect/profiles.toml`. This allows you to use a custom profiles file location.
        """
        return __config__.get('profileFile')

    @_builtins.property
    def workspace_id(self) -> Optional[str]:
        """
        Default Prefect Cloud Workspace ID.
        """
        return __config__.get('workspaceId')

