version: 2

models:
  - name: int_item_price_history_daily
    description: >
      Intermediate model that aggregates the granular price_timestamp  from
      stg_item_price_history to a daily grain.
    columns:
      - name: item_name
        description: Name of the market item.
        data_tests:
          - not_null
      - name: price_date
        description: The aggregated date (at daily grain) for the price and volume metrics.
        data_tests:
          - not_null
      - name: units_sold
        description: Total quantity of the item sold during the day.
      - name: total_estimated_trade_volume_usd
        description: >
          Estimated trade volume of the item in USD during the day. It's
          estimated because we are only have access to the median sale price,
          not the actual sale price for each unit sold.
      - name: avg_median_sale_price_usd
        description: Average median sale price of the item in USD during the day.
