models:
  - name: stg_items
    description: >
      Staging model for items data. Standardizes column names and data types from the raw items_external source.
      Many of the name column were found to be duplicate, so we kept only one of them and renamed it to item_name for clarity.
    columns:
      - name: item_name
        description: Name of the market item, including any special attributes or conditions (e.g., 'Factory New', 'StatTrak').
      - name: class_id
        description: Identifier for the item class, used to link to the dim_item_class dimension table.
      - name: market_bucket_group_id
        description: >
          String identifier for the market bucket group, used to link to the dim_item_bucket_group dimension table.
          This is a broader categorization than class_id (i.e. there are less bucket groups than classes).
        data_type: STRING
      - name: market_bucket_group_name
        description: >
          Name of the market bucket group, providing a human-readable label for the market_bucket_group_id.
          This is a broader categorization than class_id (i.e. there are less bucket groups than classes).
      - name: item_type
        description: >
          Type of the item, including ordinal classification (e.g., 'Exotic Collectible', 'Covert Rifle', 'Base Grade Container', 'Superior Agent').
          Seems to be even broader than market bucket group.
      - name: name_color
        description: Hex color code of the item name, which can indicate rarity or special attributes (e.g., pink for 'Covert' items)
      - name: is_tradable
        description: Boolean flag indicating whether the item is tradable on the market.
      - name: is_commodity
        description: >
          Boolean indicating if the item is a commodity, which means it has no distinct attributes, like a sticker capsule.
          Non-commodity items can have different variations (e.g., different wear levels, StatTrak versions) that affect their market value.
      - name: sell_listings_count
        description: Number of active sell listings for the item on the market, indicating its current supply.
      - name: sell_price_cents
        description: Lowest sell price for the item in cents, representing the current market price.
        data_type: INT64
      - name: sell_price_usd
        description: Lowest sell price for the item in USD, representing the current market price.
        data_type: NUMERIC
      - name: sale_price_usd_from_text
        description: >
          Sale price converted from its original text format (e.g. '$0.25') to a numeric value in USD, providing a standardized price for analysis.
          Represents the highest price a buyer is willing to pay for the item, which can differ from the lowest sell price.
        data_type: NUMERIC
      - name: snapshot_date
        description: Date when the item data was recorded, used for time-based analysis of market trends.
        data_type: DATE
      - name: dlt_id
        description: Unique identifier for the record, generated by dlt during data extraction, used for tracking and debugging purposes.
        data_type: STRING
      - name: dlt_load_id
        description: Identifier for the data load batch, generated by dlt, used for tracking and debugging purposes.
        data_type: STRING

  - name: stg_item_price_history
    description: >
      Staging model for item price history data. Standardizes column names and data types from the raw item_price_history_external source.
    columns:
      - name: item_name
        description: Name of the market item, including any special attributes or conditions (e.g., 'Factory New', 'StatTrak').
      - name: price_timestamp
        description: Timestamp of the price record, indicating when the price and sales volume was recorded.
      - name: price_usd
        description: Price of the item in USD at the given timestamp.
        data_type: NUMERIC
      - name: sales_volume
        description: Number of units sold at the given timestamp.
        data_type: INT64
      - name: dlt_id
        description: Unique identifier for the record, generated by dlt during data extraction, used for tracking and debugging purposes.
        data_type: STRING
      - name: dlt_load_id
        description: Identifier for the data load batch, generated by dlt, used for tracking and debugging purposes.
        data_type: STRING
